import { EquipmentSlot } from "@minecraft/server";
import { HELD } from "../config/held.js";
import { onHeldChange } from "./heldItem.js";

// Which gun item the player holds, as a number (config/held.js, generated by tools/weapons/held.cjs) in the
// player property krep:held. The resource pack's player.entity.json compares that number to tell the guns apart
// (`variable.akmb = q.property('krep:held') == 2;`), once per frame for every player each client draws: much
// cheaper than the 118 item-name lookups it made per player per frame until v1.33.14, which matters on phones.
// Written only when it changes (every write is sent to the clients near the player).

onHeldChange((player) => {
  const typeId = player.getComponent("minecraft:equippable")?.getEquipment(EquipmentSlot.Mainhand)?.typeId;
  const value = HELD[typeId] ?? 0;
  if (player.getProperty("krep:held") !== value) player.setProperty("krep:held", value);
});
