import { world, ItemStack } from "@minecraft/server";
import { WEAPONS } from "../config/weapons.js";
import { AMMO, OTHER_LORE } from "../config/ammo.js";
import { LORE } from "../config/lore.js";

// Lore on TACZ items. Guns use krep:gun.<id>.lore / krep:gun.<id>_emp.lore; ammo uses AMMO[id].lore. The text is
// the English line from TACZ-R/texts/en_US.lang as plain text (config/lore.js, generated by
// tools/weapons/lore.cjs; 2.x setLore also takes translated RawMessage: a cleanup idea, untested).
// Items the scripts make get it at once (loredItem: the empty / reloaded gun); others when a TACZ item enters a
// player's inventory (crafted, picked up, creative, /give) and when a player joins. Before v1.33.6 every
// inventory was scanned every second.
const LORE_BY_ITEM = {
  ...Object.fromEntries(Object.entries(AMMO).map(([id, ammo]) => [`krep:${id}`, ammo.lore])),
  ...OTHER_LORE,
  ...Object.fromEntries(
    Object.keys(WEAPONS).flatMap((id) => [
      [`krep:${id}`, `krep:gun.${id}.lore`],
      [`krep:${id}_emp`, `krep:gun.${id}_emp.lore`],
    ]),
  ),
};
const LORED_ITEMS = Object.keys(LORE_BY_ITEM).filter((typeId) => LORE[LORE_BY_ITEM[typeId]]);

/** A new item stack with its lore already set (for items the scripts put in a player's hand). */
export function loredItem(typeId, amount = 1) {
  const item = new ItemStack(typeId, amount);
  const lines = LORE[LORE_BY_ITEM[typeId]];
  if (lines) item.setLore(lines);
  return item;
}

/** Adds lore to the player's TACZ items that have none; only those items are written back (setItem syncs). */
function addMissingLore(player) {
  const inventory = player.getComponent("inventory")?.container;
  if (!inventory) return;
  for (let slot = 0; slot < inventory.size; slot++) {
    const item = inventory.getItem(slot);
    const lines = item && LORE[LORE_BY_ITEM[item.typeId]];
    if (!lines || item.getLore().length > 0) continue;
    try {
      item.setLore(lines);
      inventory.setItem(slot, item);
    } catch (error) {
      console.warn(`[TACZ Lore] ${item.typeId}: ${error}`);
    }
  }
}

// A TACZ item arrived or changed (not just its count): the event's slot numbering isn't documented per inventory
// type, so the inventory is checked (36 slots, only on these events).
world.afterEvents.playerInventoryItemChange.subscribe(
  ({ player, itemStack }) => {
    if (itemStack && itemStack.getLore().length === 0) addMissingLore(player);
  },
  { includeItems: LORED_ITEMS, ignoreQuantityChange: true },
);
world.afterEvents.playerSpawn.subscribe(({ player, initialSpawn }) => {
  if (initialSpawn) addMissingLore(player);
});
world.afterEvents.worldLoad.subscribe(() => world.getPlayers().forEach(addMissingLore));
