import { system, world, TicksPerSecond } from "@minecraft/server";
import { WEAPONS } from "../config/weapons.js";
import { AMMO, OTHER_LORE } from "../config/ammo.js";
import { LORE } from "../config/lore.js";

// Adds lore to TACZ items in player inventories. Guns use krep:gun.<id>.lore / krep:gun.<id>_emp.lore;
// ammo uses AMMO[id].lore. The text is the English line from TACZ-R/texts/en_US.lang, as plain text:
// this script API version (@minecraft/server 1.18.0) can't show translated lore. config/lore.js is
// generated by tools/weapons/lore.cjs.
const LORE_BY_ITEM = {
  ...Object.fromEntries(Object.entries(AMMO).map(([id, ammo]) => [`krep:${id}`, ammo.lore])),
  ...OTHER_LORE,
  ...Object.fromEntries(
    Object.keys(WEAPONS).flatMap((id) => [
      [`krep:${id}`, `krep:gun.${id}.lore`],
      [`krep:${id}_emp`, `krep:gun.${id}_emp.lore`],
    ]),
  ),
};

// Checked once a second; an item is only written back when it had no lore yet (every setItem
// is synced to the client).
system.runInterval(() => {
  for (const player of world.getAllPlayers()) {
    const inventory = player.getComponent("inventory")?.container;
    if (!inventory) continue;
    for (let slot = 0; slot < inventory.size; slot++) {
      const item = inventory.getItem(slot);
      const lines = item && LORE[LORE_BY_ITEM[item.typeId]];
      if (!lines || item.getLore().length > 0) continue;
      try {
        item.setLore(lines);
        inventory.setItem(slot, item);
      } catch (error) {
        console.warn(`[TACZ Lore] ${item.typeId}: ${error}`);
      }
    }
  }
}, TicksPerSecond);
