import { system, EquipmentSlot, Player } from "@minecraft/server";
import { getWeaponByItem } from "../config/weapons.js";
import { SLOTS, ATTACHMENT_INFO, GUN_ATTACHMENTS, MODEL_INDEX } from "../config/javaAttachments.js";
import { onHeldChange } from "../items/heldItem.js";

// Java TACZ attachments (config/javaAttachments.js, generated by tools/weapons/java-attach.mjs). Fitted at the
// attachment bench, free (user, 2026-10-05). Stored per player and gun in the dynamic property "tacz_att_<gun>"
// as {"scope": "sight_552", "muzzle": ...}. While a gun is held, each slot's model number goes to the player
// property krep:att_<slot> (0 = none): the RP render controllers in tacz_attachments.json draw that model on the
// gun. Effects: scope zoom (aimZoom.js), silencers (firing.js), recoil (recoil.js).
// Guns with Java attachments don't use the original pack's numbered parts (config/attachments.js) any more.

const key = (gunId) => `tacz_att_${gunId}`;

export const SLOT_LABEL = { scope: "Sight", muzzle: "Muzzle", grip: "Grip", stock: "Stock", laser: "Laser" };
export const hasJavaAttachments = (gunId) => !!GUN_ATTACHMENTS[gunId];
export const slotsOf = (gunId) => SLOTS.filter((s) => GUN_ATTACHMENTS[gunId]?.[s]?.length);
export const optionsOf = (gunId, slot) => GUN_ATTACHMENTS[gunId]?.[slot] ?? [];
export const infoOf = (attachmentId) => ATTACHMENT_INFO[attachmentId];

/** The gun's fitted Java attachments, e.g. { scope: "sight_552" } (only ones that still fit it). */
export function fittedJava(player, gunId) {
  let stored = {};
  try {
    stored = JSON.parse(player.getDynamicProperty(key(gunId)) ?? "{}");
  } catch {
    // a broken value counts as nothing fitted
  }
  const out = {};
  for (const s of SLOTS) if (stored[s] && optionsOf(gunId, s).includes(stored[s])) out[s] = stored[s];
  return out;
}

/** Fit (attachmentId) or remove (null) the slot's attachment, then show it. */
export function fitJava(player, gunId, slot, attachmentId) {
  const fitted = fittedJava(player, gunId);
  if (attachmentId) fitted[slot] = attachmentId;
  else delete fitted[slot];
  player.setDynamicProperty(key(gunId), Object.keys(fitted).length ? JSON.stringify(fitted) : undefined);
  syncJavaAttachments(player);
}

/** Show the held gun's Java attachments on the model (writes only what changed: every write goes to clients). */
export function syncJavaAttachments(player) {
  const typeId = player.getComponent("minecraft:equippable")?.getEquipment(EquipmentSlot.Mainhand)?.typeId;
  const weapon = getWeaponByItem(typeId);
  const gunId = weapon && hasJavaAttachments(weapon.id) ? weapon.id : null;
  const fitted = gunId ? fittedJava(player, gunId) : {};
  for (const s of SLOTS) {
    const value = (fitted[s] && MODEL_INDEX[s][`${gunId}:${fitted[s]}`]) || 0;
    if (player.getProperty(`krep:att_${s}`) !== value) player.setProperty(`krep:att_${s}`, value);
  }
  // The original pack's sight (krep:<gun>scope) is replaced on these guns: an old choice mustn't stay visible.
  if (gunId) {
    try {
      if ((player.getProperty(`krep:${gunId}scope`) ?? "nothing") !== "nothing") player.setProperty(`krep:${gunId}scope`, "nothing");
    } catch {
      // the gun has no such property
    }
  }
}
onHeldChange(syncJavaAttachments);

/** A fitted magnified scope's zoom (ACOG 2.5 ...), or undefined. Red dots and holo sights don't zoom. */
export function javaZoom(player, gunId) {
  if (!hasJavaAttachments(gunId)) return undefined;
  const info = infoOf(fittedJava(player, gunId).scope);
  return info?.magnified && info.zoom > 1 ? info.zoom : undefined;
}

export const javaSilenced = (player, gunId) => hasJavaAttachments(gunId) && !!infoOf(fittedJava(player, gunId).muzzle)?.silencer;

/** Recoil multiplier from the fitted attachments (Java's pitch / yaw multipliers, averaged per attachment). */
export function javaRecoilFactor(player, gunId) {
  if (!hasJavaAttachments(gunId)) return 1;
  let factor = 1;
  for (const id of Object.values(fittedJava(player, gunId))) {
    const r = infoOf(id)?.recoil;
    if (r) factor *= (r.pitch + r.yaw) / 2;
  }
  return factor;
}

// Experiment (v1.34.0, remove once decided): one shared ACOG model whose root bone is bound to the held gun's
// 'scope_pos' by name (TACZ-R/models/entity/attachments_test/acog_bound.geo.json), drawn on the AKM.
// "/scriptevent tacz:atttest on" shows it, "off" hides it. If it sits on the AKM's rail and moves with the gun,
// every attachment can be one shared model (about 4 MB for all 99) instead of a copy per gun (about 68 MB).
system.afterEvents.scriptEventReceive.subscribe(({ id, message, sourceEntity: player }) => {
  if (id !== "tacz:atttest" || !(player instanceof Player)) return;
  const on = message.trim() !== "off";
  player.setProperty("krep:att_test", on ? 1 : 0);
  player.sendMessage(on ? "Attachment test on: hold the AKM (shared ACOG bound to scope_pos)." : "Attachment test off.");
});
