// The held-gun number: one int property instead of ~120 item-name checks per player per frame on every client.
//
//   node tools/weapons/held.cjs        regenerate config/held.js and the RP lines (gun.mjs clone / remove do this)
//
// TACZ-B/scripts/config/held.js (generated): a number per gun item, HELD["krep:akm"] = 2, HELD["krep:akm_emp"] = 3
// (0 = no gun). items/heldGun.js writes it to the player property krep:held when what the player holds changes.
// TACZ-R/entity/player.entity.json pre_animation: `variable.akmb = q.property('krep:held') == 2;` and
// `variable.akmemp = q.property('krep:held') == 3;` (until v1.33.14: `query.get_equipped_item_name=='akm'`, a
// text lookup, 118 per player per frame).
// Numbers are stable: a gun keeps its number (2n loaded, 2n+1 empty), a new gun gets the next free one, a removed
// gun's number is freed. The property's range in TACZ-B/entities/player.json (0..255) allows 126 guns.
const fs = require("fs");
const path = require("path");

const HELD_FILE = "TACZ-B/scripts/config/held.js";
const WEAPONS_FILE = "TACZ-B/scripts/config/weapons.js";
const ENTITY_FILE = "TACZ-R/entity/player.entity.json";
const PROPERTY = "krep:held";
const MAX = 255;

/** Gun ids in config/weapons.js, in order (the keys of the WEAPONS object). */
function weaponIds(weaponsText) {
  const text = weaponsText.replace(/\r\n/g, "\n");
  const start = text.indexOf("export const WEAPONS");
  if (start < 0) throw new Error(`${WEAPONS_FILE}: no "export const WEAPONS"`);
  const end = text.indexOf("\n}));", start);
  return [...text.slice(start, end < 0 ? undefined : end).matchAll(/^  ([a-z0-9]+): \{$/gm)].map((m) => m[1]);
}

/** gun id -> n from the current held.js (empty if there is none yet). */
function currentNumbers(heldText) {
  const out = {};
  for (const m of (heldText ?? "").matchAll(/"krep:([a-z0-9]+)": (\d+),/g)) out[m[1]] = +m[2] / 2;
  return out;
}

/** n per gun: kept for guns that have one, the next free number for new guns. */
function numbers(ids, heldText) {
  const old = currentNumbers(heldText);
  const n = {};
  const used = new Set();
  // (A clone may arrive with its source's number copied: the first gun in weapons.js keeps it.)
  for (const id of ids) if (Number.isInteger(old[id]) && old[id] >= 1 && !used.has(old[id])) used.add((n[id] = old[id]));
  let next = 1;
  for (const id of ids) {
    if (n[id] !== undefined) continue;
    while (used.has(next)) next++;
    n[id] = next;
    used.add(next);
  }
  if (Math.max(0, ...Object.values(n)) * 2 + 1 > MAX) throw new Error(`more guns than krep:held can count (max ${MAX})`);
  return n;
}

function generateHeld(weaponsText, heldText) {
  const n = numbers(weaponIds(weaponsText), heldText);
  const lines = Object.entries(n)
    .sort((a, b) => a[1] - b[1])
    .flatMap(([id, k]) => [`  "krep:${id}": ${2 * k},`, `  "krep:${id}_emp": ${2 * k + 1},`]);
  return (
    `// GENERATED by tools/weapons/held.cjs from ${WEAPONS_FILE}: run it after adding or removing a gun (gun.mjs does).\n` +
    `// The value of the player property ${PROPERTY} while holding each gun item (0 = no gun); the resource pack's\n` +
    `// player.entity.json compares it instead of the item name. A gun keeps its number when others are added.\n` +
    `export const HELD = Object.freeze({\n${lines.join("\n")}\n});\n`
  );
}

/** The RP pre_animation lines for every gun, from a held.js text. */
function rewriteEntity(entityText, heldText) {
  const n = currentNumbers(heldText);
  const missing = new Set(Object.keys(n));
  const out = entityText.replace(/"variable\.([a-z0-9]+?)(b|emp) = (?:query\.get_equipped_item_name==\s*'[a-z0-9_]+'|q\.property\('krep:held'\) == \d+);"/g, (line, id, kind) => {
    if (n[id] === undefined) return line;
    if (kind === "b") missing.delete(id);
    return `"variable.${id}${kind} = q.property('${PROPERTY}') == ${2 * n[id] + (kind === "emp" ? 1 : 0)};"`;
  });
  if (missing.size) throw new Error(`${ENTITY_FILE}: no "variable.<id>b = ..." line for ${[...missing].join(", ")}`);
  return out;
}

module.exports = { generateHeld, rewriteEntity, weaponIds, HELD_FILE, WEAPONS_FILE, ENTITY_FILE, PROPERTY };

if (require.main === module) {
  const root = process.cwd();
  const read = (f) => (fs.existsSync(path.join(root, f)) ? fs.readFileSync(path.join(root, f), "utf8") : null);
  // Keep each file's line endings (a Windows checkout may have \r\n).
  const write = (f, text, like) => fs.writeFileSync(path.join(root, f), (like ?? "").includes("\r\n") ? text.replace(/\r?\n/g, "\r\n") : text);
  const oldHeld = read(HELD_FILE);
  const held = generateHeld(read(WEAPONS_FILE), oldHeld);
  write(HELD_FILE, held, oldHeld ?? read(WEAPONS_FILE));
  const entity = read(ENTITY_FILE);
  write(ENTITY_FILE, rewriteEntity(entity.replace(/\r\n/g, "\n"), held), entity);
  console.log(`wrote ${HELD_FILE} and the held-gun lines of ${ENTITY_FILE}`);
}
