// Builds TACZ-B/scripts/config/lore.js from the English lore lines in TACZ-R/texts/en_US.lang.
//
//   node tools/weapons/lore.cjs        regenerate it (gun.mjs does this when it adds or removes a gun)
//
// Why: the script API the pack uses (@minecraft/server 1.18.0) only takes plain text for item lore
// (ItemStack.setLore(string[])), at most 20 lines of 50 characters, so translated text keys can't be
// used and scripts can't read the lang files. Lore is therefore English for every language.
const fs = require("fs");
const path = require("path");

const LANG = "TACZ-R/texts/en_US.lang";
const OUT = "TACZ-B/scripts/config/lore.js";
const MAX_LINE = 50, MAX_LINES = 20;

// "§fType: Sniper Rifle \n§fGroup: ..." -> lines of at most 50 characters (colour codes carried over).
function loreLines(text) {
  const out = [];
  for (const raw of text.split("\\n")) {
    const line = raw.trim();
    if (!line) { out.push(""); continue; }
    let colour = "", rest = line;
    while (rest.length > MAX_LINE) {
      let cut = rest.lastIndexOf(" ", MAX_LINE);
      if (cut <= 0) cut = MAX_LINE;
      const part = rest.slice(0, cut).trimEnd();
      out.push(part);
      colour = (part.match(/§./g) ?? []).pop() ?? colour;
      rest = colour + rest.slice(cut).trimStart();
    }
    out.push(rest);
  }
  while (out.length && out[out.length - 1] === "") out.pop();
  return out.slice(0, MAX_LINES);
}

function generateLore(langText) {
  const entries = langText.split(/\r?\n/).filter((l) => /^[^#=]+\.lore=/.test(l)).map((l) => {
    const i = l.indexOf("=");
    return [l.slice(0, i), loreLines(l.slice(i + 1))];
  });
  const body = entries.map(([k, lines]) => `  ${JSON.stringify(k)}: [${lines.map((x) => JSON.stringify(x)).join(", ")}],`).join("\n");
  return `// GENERATED by tools/weapons/lore.cjs from ${LANG}: edit the lang file, then run it (gun.mjs does).\n` +
    `// Item lore as plain text lines (the script API can't show translated lore).\n` +
    `export const LORE = Object.freeze({\n${body}\n});\n`;
}

module.exports = { generateLore, LORE_FILE: OUT, LANG_FILE: LANG };

if (require.main === module) {
  const root = process.cwd();
  const out = path.join(root, OUT), text = generateLore(fs.readFileSync(path.join(root, LANG), "utf8"));
  // Keep the file's line endings (a Windows checkout may have \r\n).
  const crlf = fs.existsSync(out) && fs.readFileSync(out, "utf8").includes("\r\n");
  fs.writeFileSync(out, crlf ? text.split("\n").join("\r\n") : text);
  console.log(`wrote ${OUT}`);
}
