// =====================================================================================
// WEAPONS: every gun in the pack and its stats. Edit numbers here to rebalance.
// Rules shared by all guns (headshots, armor, global multipliers, hitscan range) are in
// combat.js; attachment recoil reductions in recoil.js.
//
// Used live by the scripts (change here, reload the world):
//   name          Label in the gunsmith menu.
//   category      rifle | smg | pistol | sniper | shotgun | heavy (informational).
//   damage        Damage per hit (per pellet for shotguns), at full range.
//   penetration   0..1: how much armor it ignores. Armor reduces damage by
//                 (armor points x (1 - penetration)) / 20, capped at 80%. 1 ignores armor.
//   headshot      Damage multiplier for headshots (Java TACZ values; default COMBAT.headshotMultiplier).
//   falloff       [[upToBlocks, multiplier], ...]: damage by distance; the first step that reaches
//                 the target applies, null = any distance. E.g. [[45, 1], [70, 0.81], [null, 0.75]].
//                 No falloff = full damage at any range. (From Java TACZ damage_adjust.)
//   recoil        { hip: [power, duration], ads: [power, duration] }: camera shake per shot.
//                 ads = sneaking. Fitted attachments can reduce it (recoil.js).
//   fireMode      "semi" | "burst" | "auto": the gun's only fire mode.
//   rpm           Rounds per minute. burst: { count, rpm, delay }: shots per burst, fire rate within
//                 the burst, seconds between bursts. Applied to guns with scriptFiring; the others
//                 still fire at their animation controller's rate.
//   scriptFiring  true: firing, fire rate and the ammo count run in combat/firing.js instead of the
//                 gun's BP fire controller (being rolled out one gun at a time).
//   pellets       Rays per shot (shotguns: 12). Default 1.
//   spread        { hip, ads }: pellet scatter in degrees (typical deviation from the aim;
//                 about 2 in 3 pellets land within it). ads = sneaking. Only with pellets.
//   tracers       How many of the pellets draw a smoke tracer. Default: all.
//   explosion     { power, breaksBlocks, splashDamage, splashRadius }: the shot explodes
//                 where it lands (RPG). power 4 = TNT. splashDamage hits every entity
//                 within splashRadius blocks, on top of the explosion itself.
//   recipe        Gunsmith ingredients, [item, count]. "log" accepts any wood log.
//   icon          Menu icon if not textures/items/<id>.
//   range, tracerParticles, breakableBlocks   Optional overrides of HITSCAN (combat.js).
//   storedAmmoDisplay        Shows stored ammo on the gun model (krep:bulletcache).
//
// Defined by the behavior pack JSON, listed here so everything is in one place.
// Changing these does nothing by itself; `tools/weapons/check.mjs` reports any gun whose
// pack files disagree with these values, and where to change them:
//   magazine      Rounds per magazine (functions/<id>*.mcfunction, animation controllers).
//   ammo          Item consumed on reload.
//   reload        "single": loads one round per reload (tube-fed shotguns).
//   overheat      Minigun: shots before it must cool down (no magazine).
//
// Adding a gun: add an entry here (the id is the item id without "krep:"), then the pack
// files it needs; see README "Adding a weapon". Removing: delete the entry and its files.
// =====================================================================================

// Order = order in the gunsmith menu.
// (Loosely typed for editors and type checks: entries have different optional fields.)
export const WEAPONS = /** @type {Record<string, any>} */ (Object.freeze({
  deagle: {
    name: "Desert Eagle",
    category: "pistol",
    damage: 16,
    penetration: 0.5,
    recoil: { hip: [0.045, 0.17], ads: [0.032, 0.15] },
    headshot: 1.75,
    falloff: [[15, 1], [30, 0.88], [50, 0.75], [null, 0.63]],
    fireMode: "semi",
    rpm: 300,
    magazine: 7,
    ammo: "krep:ae50",
    recipe: [
      ["diamond", 2],
      ["gold_ingot", 6],
      ["iron_ingot", 42],
      ["blaze_rod", 1],
    ],
  },
  mp5: {
    name: "MP5",
    category: "smg",
    damage: 6.5,
    penetration: 0.45,
    recoil: { hip: [0.042, 0.21], ads: [0.032, 0.2] },
    headshot: 1.25,
    falloff: [[18, 1], [40, 0.83], [65, 0.75], [null, 0.58]],
    fireMode: "auto",
    rpm: 820,
    magazine: 30,
    ammo: "krep:mm9",
    recipe: [
      ["iron_ingot", 32],
      ["lapis_lazuli", 4],
    ],
  },
  vector: {
    name: "Vector 45",
    category: "smg",
    damage: 6,
    penetration: 0.4,
    recoil: { hip: [0.026, 0.17], ads: [0.022, 0.15] },
    headshot: 1.25,
    falloff: [[15, 1], [36, 0.79], [50, 0.64], [null, 0.5]],
    fireMode: "auto",
    rpm: 1200,
    magazine: 20,
    ammo: "krep:acp45",
    recipe: [
      ["diamond", 10],
      ["gold_ingot", 12],
      ["iron_ingot", 60],
      ["lapis_lazuli", 8],
    ],
  },
  p90: {
    name: "P90",
    category: "smg",
    damage: 4,
    penetration: 0.7,
    recoil: { hip: [0.032, 0.3], ads: [0.032, 0.28] },
    headshot: 1.25,
    falloff: [[14, 1], [36, 0.82], [50, 0.73], [null, 0.55]],
    fireMode: "auto",
    rpm: 810,
    magazine: 50,
    ammo: "krep:mm5728",
    recipe: [
      ["diamond", 2],
      ["gold_ingot", 8],
      ["iron_ingot", 72],
      ["quartz", 3],
    ],
  },
  m16a1: {
    name: "M16A1",
    category: "rifle",
    damage: 6,
    penetration: 0.6,
    recoil: { hip: [0.022, 0.28], ads: [0.015, 0.27] },
    headshot: 1.5,
    falloff: [[45, 1.06], [70, 0.88], [null, 0.63]],
    fireMode: "auto",
    rpm: 750,
    magazine: 20,
    ammo: "krep:m885",
    recipe: [
      ["lapis_lazuli", 6],
      ["iron_ingot", 32],
      ["log", 6],
    ],
  },
  m16: {
    name: "M16A4",
    category: "rifle",
    damage: 6,
    penetration: 0.6,
    recoil: { hip: [0.022, 0.28], ads: [0.015, 0.27] },
    headshot: 1.35,
    falloff: [[45, 1], [70, 0.81], [null, 0.75]],
    fireMode: "burst",
    rpm: 400,
    burst: { count: 3, rpm: 937, delay: 0.4 },
    magazine: 30,
    ammo: "krep:m885",
    recipe: [
      ["lapis_lazuli", 8],
      ["iron_ingot", 36],
      ["log", 6],
    ],
  },
  hk416: {
    name: "HK416",
    category: "rifle",
    damage: 5,
    penetration: 0.6,
    recoil: { hip: [0.045, 0.25], ads: [0.035, 0.23] },
    headshot: 1.5,
    falloff: [[30, 1], [60, 0.77], [null, 0.62]],
    fireMode: "auto",
    rpm: 943,
    magazine: 30,
    ammo: "krep:m885",
    recipe: [
      ["gold_ingot", 16],
      ["iron_ingot", 64],
      ["quartz", 8],
    ],
  },
  scarh: {
    name: "SCAR-H",
    category: "rifle",
    damage: 9,
    penetration: 0.7,
    recoil: { hip: [0.032, 0.3], ads: [0.032, 0.28] },
    headshot: 1.5,
    falloff: [[35, 1], [85, 0.79], [null, 0.64]],
    fireMode: "auto",
    rpm: 570,
    magazine: 20,
    ammo: "krep:win308",
    recipe: [
      ["diamond", 2],
      ["gold_ingot", 16],
      ["iron_ingot", 96],
      ["blaze_rod", 4],
    ],
  },
  g3: {
    name: "G3",
    category: "rifle",
    damage: 9,
    penetration: 0.7,
    recoil: { hip: [0.032, 0.3], ads: [0.032, 0.28] },
    headshot: 1.5,
    falloff: [[35, 1], [80, 0.75], [null, 0.63]],
    fireMode: "semi",
    rpm: 350,
    magazine: 20,
    ammo: "krep:win308",
    recipe: [
      ["gold_ingot", 9],
      ["iron_ingot", 72],
      ["quartz", 5],
    ],
  },
  aa12: {
    name: "AA-12",
    category: "shotgun",
    damage: 2,
    penetration: 0.1,
    recoil: { hip: [0.032, 0.3], ads: [0.032, 0.28] },
    headshot: 1.33,
    falloff: [[15, 1], [30, 0.83], [null, 0.5]],
    fireMode: "semi",
    rpm: 350,
    pellets: 12,
    spread: { hip: 7.4, ads: 3.9 },
    tracers: 6,
    magazine: 10,
    ammo: "krep:gauge12",
    recipe: [
      ["diamond", 2],
      ["gold_ingot", 16],
      ["iron_ingot", 80],
      ["blaze_rod", 4],
    ],
  },
  rpg: {
    name: "RPG-7",
    category: "heavy",
    damage: 100,
    penetration: 1,
    recoil: { hip: [0.032, 0.3], ads: [0.032, 0.28] },
    headshot: 1,
    fireMode: "semi",
    rpm: 150,
    explosion: { power: 4, breaksBlocks: true, splashDamage: 10, splashRadius: 5 },
    tracerParticles: 12,
    magazine: 1,
    ammo: "krep:rpgrocket",
    recipe: [
      ["log", 24],
      ["lapis_lazuli", 16],
      ["iron_ingot", 38],
    ],
  },
  m320: {
    name: "M320",
    category: "heavy",
    damage: 9.5,
    penetration: 0.3,
    recoil: { hip: [0.032, 0.3], ads: [0.032, 0.28] },
    headshot: 1,
    fireMode: "semi",
    rpm: 150,
    explosion: { power: 4, breaksBlocks: true, splashDamage: 10, splashRadius: 5 },
    tracerParticles: 12,
    magazine: 1,
    ammo: "krep:grenade40",
    // Java TACZ recipe.
    recipe: [["gold_ingot", 15], ["iron_ingot", 50], ["lapis_lazuli", 6]],
  },
  m870: {
    name: "M870",
    category: "shotgun",
    damage: 3,
    penetration: 0.5,
    recoil: { hip: [0.032, 0.3], ads: [0.032, 0.28] },
    headshot: 1.33,
    falloff: [[18, 1], [32, 0.75], [null, 0.5]],
    fireMode: "semi",
    rpm: 180,
    pellets: 12,
    spread: { hip: 6.1, ads: 2.2 },
    tracers: 6,
    magazine: 5,
    ammo: "krep:gauge12",
    reload: "single",
    recipe: [
      ["iron_ingot", 25],
      ["log", 12],
    ],
  },
  spas12: {
    name: "SPAS-12",
    category: "shotgun",
    damage: 5.5,
    penetration: 0.35,
    recoil: { hip: [0.032, 0.3], ads: [0.032, 0.28] },
    headshot: 1.33,
    falloff: [[15, 1], [30, 0.63], [null, 0.38]],
    fireMode: "semi",
    rpm: 200,
    pellets: 8,
    spread: { hip: 6.1, ads: 2.2 },
    tracers: 6,
    magazine: 5,
    ammo: "krep:gauge12",
    reload: "single",
    // Java TACZ recipe.
    recipe: [["iron_ingot", 110], ["gold_ingot", 20], ["diamond", 2], ["lapis_lazuli", 5]],
  },
  awp: {
    name: "AWM",
    category: "sniper",
    damage: 42,
    penetration: 0.9,
    recoil: { hip: [0.045, 0.17], ads: [0.032, 0.15] },
    headshot: 2,
    falloff: [[80, 1], [160, 0.86], [null, 0.62]],
    fireMode: "semi",
    rpm: 171,
    magazine: 5,
    ammo: "krep:lapua338",
    recipe: [
      ["diamond", 10],
      ["gold_ingot", 50],
      ["iron_ingot", 250],
      ["blaze_rod", 5],
    ],
  },
  m700: {
    name: "M700",
    category: "sniper",
    damage: 24,
    penetration: 0.75,
    recoil: { hip: [0.045, 0.17], ads: [0.032, 0.15] },
    headshot: 2,
    falloff: [[48, 1], [96, 0.79], [190, 0.67], [null, 0.58]],
    fireMode: "semi",
    rpm: 180,
    magazine: 5,
    ammo: "krep:spr3006",
    // Java TACZ recipe.
    recipe: [["diamond", 1], ["gold_ingot", 4], ["iron_ingot", 45]],
  },
  kar98: {
    name: "Kar98k",
    category: "sniper",
    damage: 26,
    penetration: 0.65,
    recoil: { hip: [0.045, 0.17], ads: [0.032, 0.15] },
    headshot: 1.85,
    falloff: [[40, 1], [80, 0.85], [null, 0.58]],
    fireMode: "semi",
    rpm: 250,
    magazine: 4,
    ammo: "krep:mm792",
    // Java TACZ recipe.
    recipe: [["log", 40], ["iron_ingot", 28], ["gold_ingot", 4], ["lapis_lazuli", 12]],
  },
  g17: {
    name: "Glock-17",
    category: "pistol",
    damage: 6,
    penetration: 0.5,
    recoil: { hip: [0.045, 0.17], ads: [0.032, 0.15] },
    headshot: 1.5,
    falloff: [[18, 1.17], [45, 0.83], [null, 0.67]],
    fireMode: "semi",
    rpm: 400,
    magazine: 17,
    ammo: "krep:mm9",
    recipe: [["iron_ingot", 16]],
  },
  m1911: {
    name: "M1911",
    category: "pistol",
    damage: 11,
    penetration: 0.3,
    recoil: { hip: [0.045, 0.23], ads: [0.032, 0.2] },
    headshot: 1.5,
    falloff: [[19, 1], [40, 0.82], [null, 0.45]],
    fireMode: "semi",
    rpm: 350,
    magazine: 7,
    ammo: "krep:acp45",
    recipe: [
      ["iron_ingot", 16],
      ["log", 5],
    ],
  },
  akm: {
    name: "AKM",
    category: "rifle",
    damage: 9,
    penetration: 0.65,
    recoil: { hip: [0.042, 0.3], ads: [0.032, 0.28] },
    headshot: 1.5,
    falloff: [[30, 1], [60, 0.83], [null, 0.67]],
    fireMode: "auto",
    rpm: 600,
    magazine: 30,
    ammo: "krep:m43",
    recipe: [
      ["lapis_lazuli", 6],
      ["iron_ingot", 38],
      ["log", 8],
    ],
  },
  m4a1: {
    name: "M4A1",
    category: "rifle",
    damage: 8,
    penetration: 0.65,
    recoil: { hip: [0.035, 0.25], ads: [0.025, 0.23] },
    headshot: 1.5,
    falloff: [[25, 1], [60, 0.85], [null, 0.69]],
    fireMode: "auto",
    rpm: 810,
    scriptFiring: true,
    magazine: 30,
    ammo: "krep:m885",
    recipe: [
      ["lapis_lazuli", 6],
      ["iron_ingot", 38],
      ["log", 8],
    ],
  },
  spr15: {
    name: "SPR-15",
    category: "rifle",
    damage: 9.5,
    penetration: 0.7,
    recoil: { hip: [0.035, 0.25], ads: [0.025, 0.23] },
    headshot: 1.75,
    falloff: [[40, 1], [72, 0.8], [null, 0.7]],
    fireMode: "semi",
    rpm: 700,
    scriptFiring: true,
    magazine: 15,
    ammo: "krep:m885",
    // Java TACZ recipe.
    recipe: [["gold_ingot", 8], ["iron_ingot", 72], ["diamond", 2], ["blaze_rod", 5]],
  },
  scarl: {
    name: "SCAR-L",
    category: "rifle",
    damage: 7,
    penetration: 0.65,
    recoil: { hip: [0.027, 0.25], ads: [0.023, 0.2] },
    headshot: 1.75,
    falloff: [[30, 1], [70, 0.8], [null, 0.67]],
    fireMode: "auto",
    rpm: 650,
    magazine: 30,
    ammo: "krep:m885",
    recipe: [
      ["gold_ingot", 6],
      ["iron_ingot", 48],
      ["quartz", 3],
    ],
  },
  g36: {
    name: "G36K",
    category: "rifle",
    damage: 7,
    penetration: 0.65,
    recoil: { hip: [0.025, 0.28], ads: [0.02, 0.27] },
    headshot: 1.5,
    falloff: [[45, 1], [72, 0.86], [null, 0.79]],
    fireMode: "auto",
    rpm: 780,
    magazine: 30,
    ammo: "krep:m885",
    recipe: [
      ["gold_ingot", 16],
      ["iron_ingot", 64],
      ["quartz", 8],
    ],
  },
  mp7: {
    name: "MP7",
    category: "smg",
    damage: 4,
    penetration: 0.7,
    recoil: { hip: [0.037, 0.2], ads: [0.032, 0.2] },
    headshot: 1.25,
    fireMode: "auto",
    rpm: 950,
    magazine: 40,
    ammo: "krep:mm4630",
    recipe: [
      ["iron_ingot", 50],
      ["gold_ingot", 10],
      ["quartz", 3],
      ["diamond", 1],
    ],
  },
  minigun: {
    name: "M134 Minigun",
    category: "heavy",
    damage: 8,
    penetration: 0.5,
    recoil: { hip: [0.022, 0.28], ads: [0.015, 0.27] },
    headshot: 1.5,
    falloff: [[50, 1], [95, 0.88], [null, 0.75]],
    fireMode: "auto",
    rpm: 1200,
    magazine: null,
    ammo: "krep:ammobox",
    overheat: 100,
    recipe: [
      ["iron_ingot", 320],
      ["blaze_rod", 10],
      ["gold_ingot", 80],
      ["netherite_ingot", 10],
      ["diamond", 40],
    ],
  },
  uzi: {
    name: "Uzi",
    category: "smg",
    damage: 5,
    penetration: 0.3,
    recoil: { hip: [0.022, 0.28], ads: [0.015, 0.27] },
    headshot: 1.25,
    falloff: [[24, 1], [50, 0.85], [null, 0.62]],
    fireMode: "auto",
    rpm: 600,
    magazine: 20,
    ammo: "krep:mm9",
    recipe: [["iron_ingot", 32]],
  },
  g18: {
    name: "Glock 18",
    category: "pistol",
    damage: 3,
    penetration: 0.3,
    recoil: { hip: [0.055, 0.2], ads: [0.042, 0.17] },
    headshot: 1.5,
    fireMode: "auto",
    rpm: 1100,
    magazine: 17,
    ammo: "krep:mm9",
    recipe: [["iron_ingot", 32]],
  },
  db: {
    name: "Double Barrel",
    category: "shotgun",
    damage: 3,
    penetration: 0.3,
    recoil: { hip: [0.032, 0.3], ads: [0.032, 0.28] },
    headshot: 1.25,
    falloff: [[5, 1], [9, 0.75], [null, 0.5]],
    fireMode: "burst",
    rpm: 150,
    burst: { count: 2, rpm: 600, delay: 0.5 },
    pellets: 12,
    spread: { hip: 6.1, ads: 2.2 },
    tracers: 6,
    magazine: 2,
    ammo: "krep:gauge12",
    recipe: [
      ["iron_ingot", 8],
      ["log", 8],
    ],
  },
  dblong: {
    name: "DB-4 Ursus",
    category: "shotgun",
    damage: 2,
    penetration: 0.45,
    recoil: { hip: [0.032, 0.3], ads: [0.032, 0.28] },
    headshot: 1.2,
    falloff: [[16, 1], [24, 0.83], [null, 0.5]],
    fireMode: "semi",
    rpm: 100,
    pellets: 10,
    spread: { hip: 6.1, ads: 2.2 },
    tracers: 6,
    magazine: 2,
    ammo: "krep:gauge12",
    // Java TACZ recipe.
    recipe: [["iron_ingot", 14], ["log", 10]],
  },
  deagleg: {
    name: "Golden Desert Eagle",
    category: "pistol",
    damage: 12,
    penetration: 0.7,
    recoil: { hip: [0.045, 0.17], ads: [0.032, 0.15] },
    headshot: 1.8,
    falloff: [[18, 1], [36, 0.92], [55, 0.75], [null, 0.58]],
    fireMode: "semi",
    rpm: 350,
    magazine: 9,
    ammo: "krep:mag357",
    recipe: [
      ["iron_ingot", 16],
      ["blaze_rod", 1],
      ["gold_ingot", 32],
      ["diamond", 1],
    ],
  },
  saiga12: {
    name: "Saiga 12",
    category: "shotgun",
    damage: 2,
    penetration: 0.3,
    recoil: { hip: [0.042, 0.35], ads: [0.052, 0.32] },
    headshot: 1.33,
    fireMode: "semi",
    rpm: 300,
    pellets: 12,
    spread: { hip: 6.1, ads: 2.2 },
    tracers: 6,
    magazine: 5,
    ammo: "krep:gauge12",
    recipe: [
      ["iron_ingot", 23],
      ["quartz", 4],
    ],
  },
  fal: {
    name: "FAL",
    category: "rifle",
    damage: 9,
    penetration: 0.7,
    recoil: { hip: [0.042, 0.36], ads: [0.038, 0.32] },
    headshot: 1.8,
    falloff: [[45, 1], [90, 0.73], [null, 0.62]],
    fireMode: "semi",
    rpm: 350,
    magazine: 20,
    ammo: "krep:win308",
    recipe: [
      ["gold_ingot", 26],
      ["iron_ingot", 64],
      ["diamond", 2],
    ],
  },
  qbz95: {
    name: "QBZ-95",
    category: "rifle",
    damage: 7,
    penetration: 0.7,
    recoil: { hip: [0.022, 0.28], ads: [0.015, 0.27] },
    headshot: 1.5,
    falloff: [[25, 1], [45, 0.8], [null, 0.6]],
    fireMode: "auto",
    rpm: 660,
    magazine: 30,
    ammo: "krep:mm5842",
    recipe: [
      ["iron_ingot", 40],
      ["log", 6],
      ["lapis_lazuli", 8],
      ["gold_ingot", 3],
    ],
  },
  ump: {
    name: "UMP-45",
    category: "smg",
    damage: 6.7,
    penetration: 0.4,
    recoil: { hip: [0.022, 0.28], ads: [0.015, 0.27] },
    headshot: 1.5,
    falloff: [[30, 1], [55, 0.78], [null, 0.61]],
    fireMode: "auto",
    rpm: 660,
    magazine: 25,
    ammo: "krep:acp45",
    icon: "textures/items/ump45",
    recipe: [
      ["iron_ingot", 62],
      ["gold_ingot", 5],
      ["quartz", 3],
    ],
  },
  b93: {
    name: "B93R",
    category: "pistol",
    damage: 4,
    penetration: 0.4,
    recoil: { hip: [0.032, 0.28], ads: [0.025, 0.27] },
    headshot: 1.25,
    falloff: [[16, 1], [32, 0.8], [48, 0.53], [null, 0.4]],
    fireMode: "burst",
    rpm: 900,
    burst: { count: 3, rpm: 900, delay: 0.4 },
    magazine: 20,
    ammo: "krep:mm9",
    recipe: [
      ["iron_ingot", 21],
      ["log", 5],
      ["lapis_lazuli", 2],
    ],
  },
  sks: {
    name: "SKS",
    category: "sniper",
    damage: 11,
    penetration: 0.65,
    recoil: { hip: [0.034, 0.28], ads: [0.025, 0.3] },
    headshot: 2,
    falloff: [[55, 1], [110, 0.82], [null, 0.64]],
    fireMode: "semi",
    rpm: 510,
    magazine: 10,
    ammo: "krep:m43",
    recipe: [
      ["iron_ingot", 40],
      ["lapis_lazuli", 8],
      ["log", 12],
    ],
  },
  mk14: {
    name: "MK14",
    category: "sniper",
    damage: 13,
    penetration: 0.7,
    recoil: { hip: [0.067, 0.2], ads: [0.057, 0.17] },
    headshot: 1.75,
    falloff: [[60, 1], [120, 0.84], [null, 0.66]],
    fireMode: "semi",
    rpm: 300,
    magazine: 20,
    ammo: "krep:win308",
    recipe: [
      ["iron_ingot", 62],
      ["gold_ingot", 20],
      ["diamond", 4],
      ["blaze_rod", 2],
    ],
  },
  qbz191: {
    name: "QBZ-191",
    category: "rifle",
    damage: 7,
    penetration: 0.7,
    recoil: { hip: [0.022, 0.28], ads: [0.015, 0.27] },
    headshot: 1.5,
    falloff: [[40, 1], [75, 0.8], [null, 0.6]],
    fireMode: "auto",
    rpm: 750,
    magazine: 30,
    ammo: "krep:mm5842",
    recipe: [
      ["iron_ingot", 64],
      ["lapis_lazuli", 16],
      ["gold_ingot", 8],
      ["quartz", 8],
    ],
  },
  type81: {
    name: "Type-81",
    category: "rifle",
    damage: 9,
    penetration: 0.65,
    recoil: { hip: [0.06, 0.2], ads: [0.047, 0.17] },
    headshot: 1.5,
    falloff: [[25, 1], [55, 0.78], [null, 0.5]],
    fireMode: "auto",
    rpm: 630,
    magazine: 30,
    ammo: "krep:m43",
    recipe: [
      ["iron_ingot", 28],
      ["log", 10],
    ],
  },
  rpk: {
    name: "RPK",
    category: "rifle",
    damage: 9.5,
    penetration: 0.7,
    recoil: { hip: [0.06, 0.2], ads: [0.047, 0.17] },
    headshot: 1.5,
    falloff: [[36, 1], [64, 0.7], [null, 0.6]],
    fireMode: "auto",
    rpm: 630,
    magazine: 40,
    ammo: "krep:m43",
    // Java TACZ recipe.
    recipe: [["iron_ingot", 56], ["gold_ingot", 8], ["quartz", 8], ["log", 12]],
  },
  evolys: {
    name: "Evolys",
    category: "heavy",
    damage: 10,
    penetration: 0.6,
    recoil: { hip: [0.064, 0.2], ads: [0.047, 0.17] },
    headshot: 1.6,
    falloff: [[40, 1], [80, 0.67], [null, 0.5]],
    fireMode: "auto",
    rpm: 750,
    magazine: 75,
    ammo: "krep:win308",
    storedAmmoDisplay: true,
    recipe: [
      ["iron_ingot", 128],
      ["gold_ingot", 30],
      ["diamond", 6],
      ["blaze_rod", 5],
    ],
  },
  m249: {
    name: "M249",
    category: "heavy",
    damage: 7,
    penetration: 0.65,
    recoil: { hip: [0.06, 0.2], ads: [0.047, 0.17] },
    headshot: 1.5,
    falloff: [[35, 0.93], [80, 0.73], [null, 0.6]],
    fireMode: "auto",
    rpm: 750,
    magazine: 100,
    ammo: "krep:m885",
    storedAmmoDisplay: true,
    recipe: [
      ["iron_ingot", 110],
      ["gold_ingot", 16],
      ["diamond", 4],
      ["blaze_rod", 2],
    ],
  },
  t50: {
    name: "Timeless 50",
    category: "pistol",
    damage: 16,
    penetration: 0.5,
    recoil: { hip: [0.022, 0.28], ads: [0.015, 0.27] },
    headshot: 1.5,
    falloff: [[20, 1.07], [50, 0.93], [null, 0.6]],
    fireMode: "semi",
    rpm: 300,
    magazine: 8,
    ammo: "krep:ae50",
    recipe: [
      ["iron_ingot", 48],
      ["gold_ingot", 6],
      ["diamond", 1],
    ],
  },
  cp: {
    name: "Colt Python",
    category: "pistol",
    damage: 12,
    penetration: 0.7,
    recoil: { hip: [0.069, 0.28], ads: [0.055, 0.27] },
    headshot: 1.75,
    fireMode: "semi",
    rpm: 150,
    magazine: 6,
    ammo: "krep:mag357",
    recipe: [
      ["iron_ingot", 28],
      ["gold_ingot", 4],
      ["lapis_lazuli", 2],
    ],
  },
  taurus943: {
    name: "Taurus 943",
    category: "pistol",
    damage: 6,
    penetration: 0.55,
    recoil: { hip: [0.069, 0.28], ads: [0.055, 0.27] },
    falloff: [[15, 1], [25, 0.75], [30, 0.5], [null, 0.5]],
    headshot: 1.5,
    fireMode: "semi",
    rpm: 180,
    magazine: 8,
    ammo: "krep:wmr22",
    recipe: [
      ["iron_ingot", 28],
      ["gold_ingot", 4],
      ["lapis_lazuli", 2],
    ],
  },
  taurus500: {
    name: "Raging Hunter",
    category: "pistol",
    damage: 40,
    penetration: 0.8,
    recoil: { hip: [0.069, 0.28], ads: [0.055, 0.27] },
    falloff: [[40, 1], [55, 0.75], [75, 0.5], [null, 0.38]],
    headshot: 2,
    fireMode: "semi",
    rpm: 120,
    magazine: 5,
    ammo: "krep:mag500",
    // Java TACZ recipe.
    recipe: [["diamond", 8], ["gold_ingot", 65], ["iron_ingot", 85], ["blaze_rod", 4]],
  },
  rhino357: {
    name: "Rhino 357",
    category: "pistol",
    damage: 10.5,
    penetration: 0.6,
    recoil: { hip: [0.069, 0.28], ads: [0.055, 0.27] },
    falloff: [[25, 1], [35, 0.81], [50, 0.57], [null, 0.57]],
    headshot: 1.75,
    fireMode: "semi",
    rpm: 200,
    magazine: 6,
    ammo: "krep:mag357",
    // Java TACZ recipe.
    recipe: [["lapis_lazuli", 8], ["gold_ingot", 4], ["iron_ingot", 32], ["log", 5]],
  },
  m1014: {
    name: "M1014",
    category: "shotgun",
    damage: 3,
    penetration: 0.4,
    recoil: { hip: [0.032, 0.3], ads: [0.032, 0.28] },
    headshot: 1.33,
    falloff: [[14, 1], [28, 0.8], [null, 0.6]],
    fireMode: "semi",
    rpm: 200,
    pellets: 12,
    spread: { hip: 6.1, ads: 2.2 },
    tracers: 6,
    magazine: 7,
    ammo: "krep:gauge12",
    storedAmmoDisplay: true,
    reload: "single",
    recipe: [
      ["iron_ingot", 62],
      ["gold_ingot", 12],
      ["diamond", 1],
      ["lapis_lazuli", 2],
    ],
  },
  p320: {
    name: "P320",
    category: "pistol",
    damage: 10,
    penetration: 0.3,
    recoil: { hip: [0.057, 0.2], ads: [0.037, 0.17] },
    headshot: 1.75,
    falloff: [[20, 1], [50, 0.7], [null, 0.5]],
    fireMode: "semi",
    rpm: 450,
    magazine: 12,
    ammo: "krep:acp45",
    recipe: [
      ["iron_ingot", 28],
      ["gold_ingot", 4],
      ["lapis_lazuli", 2],
    ],
  },
  mk23: {
    name: "MK23",
    category: "pistol",
    damage: 12,
    penetration: 0.5,
    recoil: { hip: [0.057, 0.2], ads: [0.037, 0.17] },
    headshot: 1.75,
    falloff: [[20, 1], [50, 0.92], [null, 0.75]],
    fireMode: "semi",
    rpm: 50,
    magazine: 12,
    ammo: "krep:acp45",
    // Java TACZ recipe.
    recipe: [["gold_ingot", 4], ["iron_ingot", 36], ["lapis_lazuli", 2]],
  },
  cz75: {
    name: "CZ75",
    category: "pistol",
    damage: 5,
    penetration: 0.5,
    recoil: { hip: [0.057, 0.2], ads: [0.037, 0.17] },
    headshot: 1.3,
    falloff: [[15, 1], [35, 0.8], [null, 0.6]],
    fireMode: "auto",
    rpm: 900,
    magazine: 16,
    ammo: "krep:mm9",
    // Java TACZ recipe.
    recipe: [["iron_ingot", 17]],
  },
  m9a4: {
    name: "M9A4",
    category: "pistol",
    damage: 6,
    penetration: 0.3,
    recoil: { hip: [0.057, 0.2], ads: [0.037, 0.17] },
    headshot: 1.5,
    falloff: [[18, 1.17], [45, 0.83], [null, 0.67]],
    fireMode: "semi",
    rpm: 400,
    magazine: 17,
    ammo: "krep:mm9",
    // Java TACZ recipe.
    recipe: [["iron_ingot", 16]],
  },
  m107: {
    name: "M107",
    category: "sniper",
    damage: 55,
    penetration: 0.8,
    recoil: { hip: [0.045, 0.17], ads: [0.032, 0.15] },
    headshot: 1.5,
    falloff: [[65, 0.91], [120, 0.73], [null, 0.64]],
    fireMode: "semi",
    rpm: 400,
    magazine: 10,
    ammo: "krep:bmg50",
    recipe: [
      ["diamond", 18],
      ["gold_ingot", 64],
      ["netherite_ingot", 3],
      ["iron_ingot", 320],
      ["blaze_rod", 5],
    ],
  },
  m95b: {
    name: "M95",
    category: "sniper",
    damage: 75,
    penetration: 1,
    recoil: { hip: [0.045, 0.17], ads: [0.032, 0.15] },
    headshot: 2.5,
    falloff: [[75, 1], [150, 0.87], [null, 0.67]],
    fireMode: "semi",
    rpm: 151,
    magazine: 5,
    ammo: "krep:bmg50",
    // Java TACZ recipe.
    recipe: [["diamond", 15], ["gold_ingot", 60], ["netherite_ingot", 3], ["iron_ingot", 300], ["blaze_rod", 5]],
  },
}));

/** The gun for an item id ("krep:m4a1" or the empty variant "krep:m4a1_emp"), or undefined. */
export function getWeaponByItem(typeId) {
  if (!typeId?.startsWith("krep:")) return undefined;
  const id = typeId.slice(5).replace(/_emp$/, "");
  return WEAPONS[id] ? { id, ...WEAPONS[id] } : undefined;
}

export function getWeapon(id) {
  return WEAPONS[id] ? { id, ...WEAPONS[id] } : undefined;
}
