clear @s[m=!c,scores={aa12=9},hasitem={item=krep:ammoboxc,quantity=0}] krep:gauge12 0 1
clear @s[m=!c,scores={aa12=8},hasitem={item=krep:ammoboxc,quantity=0}] krep:gauge12 0 2
clear @s[m=!c,scores={aa12=7},hasitem={item=krep:ammoboxc,quantity=0}] krep:gauge12 0 3
clear @s[m=!c,scores={aa12=6},hasitem={item=krep:ammoboxc,quantity=0}] krep:gauge12 0 4
clear @s[m=!c,scores={aa12=5},hasitem={item=krep:ammoboxc,quantity=0}] krep:gauge12 0 5
clear @s[m=!c,scores={aa12=4},hasitem={item=krep:ammoboxc,quantity=0}] krep:gauge12 0 6
clear @s[m=!c,scores={aa12=3},hasitem={item=krep:ammoboxc,quantity=0}] krep:gauge12 0 7
clear @s[m=!c,scores={aa12=1},hasitem={item=krep:ammoboxc,quantity=0}] krep:gauge12 0 8
clear @s[m=!c,scores={aa12=1},hasitem={item=krep:ammoboxc,quantity=0}] krep:gauge12 0 9
clear @s[m=!c,scores={aa12=0},hasitem={item=krep:ammoboxc,quantity=0}] krep:gauge12 0 10