event entity @s[hasitem=[{item=krep:gauge12,quantity=0},{item=krep:ammoboxc,quantity=0}]] aa12reload0
event entity @s[hasitem=[{item=krep:gauge12,quantity=1},{item=krep:ammoboxc,quantity=0}]] aa12reload1
event entity @s[hasitem=[{item=krep:gauge12,quantity=2},{item=krep:ammoboxc,quantity=0}]] aa12reload2
event entity @s[hasitem=[{item=krep:gauge12,quantity=3},{item=krep:ammoboxc,quantity=0}]] aa12reload3
event entity @s[hasitem=[{item=krep:gauge12,quantity=4},{item=krep:ammoboxc,quantity=0}]] aa12reload4
event entity @s[hasitem=[{item=krep:gauge12,quantity=5},{item=krep:ammoboxc,quantity=0}]] aa12reload5
event entity @s[hasitem=[{item=krep:gauge12,quantity=6},{item=krep:ammoboxc,quantity=0}]] aa12reload6
event entity @s[hasitem=[{item=krep:gauge12,quantity=7},{item=krep:ammoboxc,quantity=0}]] aa12reload7
event entity @s[hasitem=[{item=krep:gauge12,quantity=8},{item=krep:ammoboxc,quantity=0}]] aa12reload8
event entity @s[hasitem=[{item=krep:gauge12,quantity=9},{item=krep:ammoboxc,quantity=0}]] aa12reload9
event entity @s[hasitem=[{item=krep:gauge12,quantity=10..},{item=krep:ammoboxc,quantity=0}]] aa12reload10
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] aa12reload10