event entity @s[hasitem=[{item=krep:m43,quantity=0},{item=krep:ammoboxc,quantity=0}]] akmreload0
event entity @s[hasitem=[{item=krep:m43,quantity=1},{item=krep:ammoboxc,quantity=0}]] akmreload1
event entity @s[hasitem=[{item=krep:m43,quantity=2},{item=krep:ammoboxc,quantity=0}]] akmreload2
event entity @s[hasitem=[{item=krep:m43,quantity=3},{item=krep:ammoboxc,quantity=0}]] akmreload3
event entity @s[hasitem=[{item=krep:m43,quantity=4},{item=krep:ammoboxc,quantity=0}]] akmreload4
event entity @s[hasitem=[{item=krep:m43,quantity=5},{item=krep:ammoboxc,quantity=0}]] akmreload5
event entity @s[hasitem=[{item=krep:m43,quantity=6},{item=krep:ammoboxc,quantity=0}]] akmreload6
event entity @s[hasitem=[{item=krep:m43,quantity=7},{item=krep:ammoboxc,quantity=0}]] akmreload7
event entity @s[hasitem=[{item=krep:m43,quantity=8},{item=krep:ammoboxc,quantity=0}]] akmreload8
event entity @s[hasitem=[{item=krep:m43,quantity=9},{item=krep:ammoboxc,quantity=0}]] akmreload9
event entity @s[hasitem=[{item=krep:m43,quantity=10},{item=krep:ammoboxc,quantity=0}]] akmreload10
event entity @s[hasitem=[{item=krep:m43,quantity=11},{item=krep:ammoboxc,quantity=0}]] akmreload11
event entity @s[hasitem=[{item=krep:m43,quantity=12},{item=krep:ammoboxc,quantity=0}]] akmreload12
event entity @s[hasitem=[{item=krep:m43,quantity=13},{item=krep:ammoboxc,quantity=0}]] akmreload13
event entity @s[hasitem=[{item=krep:m43,quantity=14},{item=krep:ammoboxc,quantity=0}]] akmreload14
event entity @s[hasitem=[{item=krep:m43,quantity=15},{item=krep:ammoboxc,quantity=0}]] akmreload15
event entity @s[hasitem=[{item=krep:m43,quantity=16},{item=krep:ammoboxc,quantity=0}]] akmreload16
event entity @s[hasitem=[{item=krep:m43,quantity=17},{item=krep:ammoboxc,quantity=0}]] akmreload17
event entity @s[hasitem=[{item=krep:m43,quantity=18},{item=krep:ammoboxc,quantity=0}]] akmreload18
event entity @s[hasitem=[{item=krep:m43,quantity=19},{item=krep:ammoboxc,quantity=0}]] akmreload19
event entity @s[hasitem=[{item=krep:m43,quantity=20},{item=krep:ammoboxc,quantity=0}]] akmreload20
event entity @s[hasitem=[{item=krep:m43,quantity=21},{item=krep:ammoboxc,quantity=0}]] akmreload21
event entity @s[hasitem=[{item=krep:m43,quantity=22},{item=krep:ammoboxc,quantity=0}]] akmreload22
event entity @s[hasitem=[{item=krep:m43,quantity=23},{item=krep:ammoboxc,quantity=0}]] akmreload23
event entity @s[hasitem=[{item=krep:m43,quantity=24},{item=krep:ammoboxc,quantity=0}]] akmreload24
event entity @s[hasitem=[{item=krep:m43,quantity=25},{item=krep:ammoboxc,quantity=0}]] akmreload25
event entity @s[hasitem=[{item=krep:m43,quantity=26},{item=krep:ammoboxc,quantity=0}]] akmreload26
event entity @s[hasitem=[{item=krep:m43,quantity=27},{item=krep:ammoboxc,quantity=0}]] akmreload27
event entity @s[hasitem=[{item=krep:m43,quantity=28},{item=krep:ammoboxc,quantity=0}]] akmreload28
event entity @s[hasitem=[{item=krep:m43,quantity=29},{item=krep:ammoboxc,quantity=0}]] akmreload29
event entity @s[hasitem=[{item=krep:m43,quantity=30..},{item=krep:ammoboxc,quantity=0}]] akmreload30
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] akmreload30