clear @s[m=!c,scores={akm=29},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 1
clear @s[m=!c,scores={akm=28},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 2
clear @s[m=!c,scores={akm=27},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 3
clear @s[m=!c,scores={akm=26},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 4
clear @s[m=!c,scores={akm=25},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 5
clear @s[m=!c,scores={akm=24},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 6
clear @s[m=!c,scores={akm=23},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 7
clear @s[m=!c,scores={akm=22},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 8
clear @s[m=!c,scores={akm=21},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 9
clear @s[m=!c,scores={akm=20},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 10
clear @s[m=!c,scores={akm=19},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 11
clear @s[m=!c,scores={akm=18},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 12
clear @s[m=!c,scores={akm=17},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 13
clear @s[m=!c,scores={akm=16},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 14
clear @s[m=!c,scores={akm=15},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 15
clear @s[m=!c,scores={akm=14},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 16
clear @s[m=!c,scores={akm=13},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 17
clear @s[m=!c,scores={akm=12},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 18
clear @s[m=!c,scores={akm=11},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 19
clear @s[m=!c,scores={akm=10},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 20
clear @s[m=!c,scores={akm=9},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 21
clear @s[m=!c,scores={akm=8},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 22
clear @s[m=!c,scores={akm=7},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 23
clear @s[m=!c,scores={akm=6},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 24
clear @s[m=!c,scores={akm=5},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 25
clear @s[m=!c,scores={akm=4},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 26
clear @s[m=!c,scores={akm=3},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 27
clear @s[m=!c,scores={akm=2},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 28
clear @s[m=!c,scores={akm=1},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 29
clear @s[m=!c,scores={akm=0},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 30