event entity @s[hasitem=[{item=krep:mm9,quantity=0},{item=krep:ammoboxc,quantity=0}]] b93reload0
event entity @s[hasitem=[{item=krep:mm9,quantity=1},{item=krep:ammoboxc,quantity=0}]] b93reload1
event entity @s[hasitem=[{item=krep:mm9,quantity=2},{item=krep:ammoboxc,quantity=0}]] b93reload2
event entity @s[hasitem=[{item=krep:mm9,quantity=3},{item=krep:ammoboxc,quantity=0}]] b93reload3
event entity @s[hasitem=[{item=krep:mm9,quantity=4},{item=krep:ammoboxc,quantity=0}]] b93reload4
event entity @s[hasitem=[{item=krep:mm9,quantity=5},{item=krep:ammoboxc,quantity=0}]] b93reload5
event entity @s[hasitem=[{item=krep:mm9,quantity=6},{item=krep:ammoboxc,quantity=0}]] b93reload6
event entity @s[hasitem=[{item=krep:mm9,quantity=7},{item=krep:ammoboxc,quantity=0}]] b93reload7
event entity @s[hasitem=[{item=krep:mm9,quantity=8},{item=krep:ammoboxc,quantity=0}]] b93reload8
event entity @s[hasitem=[{item=krep:mm9,quantity=9},{item=krep:ammoboxc,quantity=0}]] b93reload9
event entity @s[hasitem=[{item=krep:mm9,quantity=10},{item=krep:ammoboxc,quantity=0}]] b93reload10
event entity @s[hasitem=[{item=krep:mm9,quantity=11},{item=krep:ammoboxc,quantity=0}]] b93reload11
event entity @s[hasitem=[{item=krep:mm9,quantity=12},{item=krep:ammoboxc,quantity=0}]] b93reload12
event entity @s[hasitem=[{item=krep:mm9,quantity=13},{item=krep:ammoboxc,quantity=0}]] b93reload13
event entity @s[hasitem=[{item=krep:mm9,quantity=14},{item=krep:ammoboxc,quantity=0}]] b93reload14
event entity @s[hasitem=[{item=krep:mm9,quantity=15},{item=krep:ammoboxc,quantity=0}]] b93reload15
event entity @s[hasitem=[{item=krep:mm9,quantity=16},{item=krep:ammoboxc,quantity=0}]] b93reload16
event entity @s[hasitem=[{item=krep:mm9,quantity=17},{item=krep:ammoboxc,quantity=0}]] b93reload17
event entity @s[hasitem=[{item=krep:mm9,quantity=18},{item=krep:ammoboxc,quantity=0}]] b93reload18
event entity @s[hasitem=[{item=krep:mm9,quantity=19},{item=krep:ammoboxc,quantity=0}]] b93reload19
event entity @s[hasitem=[{item=krep:mm9,quantity=20..},{item=krep:ammoboxc,quantity=0}]] b93reload20
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] b93reload20