clear @s[m=!c,scores={b93=19},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 1
clear @s[m=!c,scores={b93=18},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 2
clear @s[m=!c,scores={b93=17},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 3
clear @s[m=!c,scores={b93=16},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 4
clear @s[m=!c,scores={b93=15},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 5
clear @s[m=!c,scores={b93=14},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 6
clear @s[m=!c,scores={b93=13},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 7
clear @s[m=!c,scores={b93=12},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 8
clear @s[m=!c,scores={b93=11},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 9
clear @s[m=!c,scores={b93=10},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 10
clear @s[m=!c,scores={b93=9},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 11
clear @s[m=!c,scores={b93=8},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 12
clear @s[m=!c,scores={b93=7},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 13
clear @s[m=!c,scores={b93=6},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 14
clear @s[m=!c,scores={b93=5},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 15
clear @s[m=!c,scores={b93=4},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 16
clear @s[m=!c,scores={b93=3},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 17
clear @s[m=!c,scores={b93=2},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 18
clear @s[m=!c,scores={b93=1},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 19
clear @s[m=!c,scores={b93=0},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 20