clear @s[m=!c,scores={cz75=16},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 1
clear @s[m=!c,scores={cz75=15},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 2
clear @s[m=!c,scores={cz75=14},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 3
clear @s[m=!c,scores={cz75=13},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 4
clear @s[m=!c,scores={cz75=12},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 5
clear @s[m=!c,scores={cz75=11},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 6
clear @s[m=!c,scores={cz75=10},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 7
clear @s[m=!c,scores={cz75=9},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 8
clear @s[m=!c,scores={cz75=8},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 9
clear @s[m=!c,scores={cz75=7},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 10
clear @s[m=!c,scores={cz75=6},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 11
clear @s[m=!c,scores={cz75=5},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 12
clear @s[m=!c,scores={cz75=4},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 13
clear @s[m=!c,scores={cz75=3},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 14
clear @s[m=!c,scores={cz75=2},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 15
clear @s[m=!c,scores={cz75=1},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 16
clear @s[m=!c,scores={cz75=0},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 17