event entity @s[hasitem=[{item=krep:mm9,quantity=0},{item=krep:ammoboxc,quantity=0}]] cz75reload0
event entity @s[hasitem=[{item=krep:mm9,quantity=1},{item=krep:ammoboxc,quantity=0}]] cz75reload1
event entity @s[hasitem=[{item=krep:mm9,quantity=2},{item=krep:ammoboxc,quantity=0}]] cz75reload2
event entity @s[hasitem=[{item=krep:mm9,quantity=3},{item=krep:ammoboxc,quantity=0}]] cz75reload3
event entity @s[hasitem=[{item=krep:mm9,quantity=4},{item=krep:ammoboxc,quantity=0}]] cz75reload4
event entity @s[hasitem=[{item=krep:mm9,quantity=5},{item=krep:ammoboxc,quantity=0}]] cz75reload5
event entity @s[hasitem=[{item=krep:mm9,quantity=6},{item=krep:ammoboxc,quantity=0}]] cz75reload6
event entity @s[hasitem=[{item=krep:mm9,quantity=7},{item=krep:ammoboxc,quantity=0}]] cz75reload7
event entity @s[hasitem=[{item=krep:mm9,quantity=8},{item=krep:ammoboxc,quantity=0}]] cz75reload8
event entity @s[hasitem=[{item=krep:mm9,quantity=9},{item=krep:ammoboxc,quantity=0}]] cz75reload9
event entity @s[hasitem=[{item=krep:mm9,quantity=10},{item=krep:ammoboxc,quantity=0}]] cz75reload10
event entity @s[hasitem=[{item=krep:mm9,quantity=11},{item=krep:ammoboxc,quantity=0}]] cz75reload11
event entity @s[hasitem=[{item=krep:mm9,quantity=12},{item=krep:ammoboxc,quantity=0}]] cz75reload12
event entity @s[hasitem=[{item=krep:mm9,quantity=13},{item=krep:ammoboxc,quantity=0}]] cz75reload13
event entity @s[hasitem=[{item=krep:mm9,quantity=14},{item=krep:ammoboxc,quantity=0}]] cz75reload14
event entity @s[hasitem=[{item=krep:mm9,quantity=15},{item=krep:ammoboxc,quantity=0}]] cz75reload15
event entity @s[hasitem=[{item=krep:mm9,quantity=16..},{item=krep:ammoboxc,quantity=0}]] cz75reload16
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] cz75reload16