clear @s[m=!c,scores={deagleg=8},hasitem={item=krep:ammoboxc,quantity=0}] krep:mag357 0 1
clear @s[m=!c,scores={deagleg=7},hasitem={item=krep:ammoboxc,quantity=0}] krep:mag357 0 2
clear @s[m=!c,scores={deagleg=6},hasitem={item=krep:ammoboxc,quantity=0}] krep:mag357 0 3
clear @s[m=!c,scores={deagleg=5},hasitem={item=krep:ammoboxc,quantity=0}] krep:mag357 0 4
clear @s[m=!c,scores={deagleg=4},hasitem={item=krep:ammoboxc,quantity=0}] krep:mag357 0 5
clear @s[m=!c,scores={deagleg=3},hasitem={item=krep:ammoboxc,quantity=0}] krep:mag357 0 6
clear @s[m=!c,scores={deagleg=2},hasitem={item=krep:ammoboxc,quantity=0}] krep:mag357 0 7
clear @s[m=!c,scores={deagleg=1},hasitem={item=krep:ammoboxc,quantity=0}] krep:mag357 0 8
clear @s[m=!c,scores={deagleg=0},hasitem={item=krep:ammoboxc,quantity=0}] krep:mag357 0 9