event entity @s[hasitem=[{item=krep:mag357,quantity=0},{item=krep:ammoboxc,quantity=0}]] deaglegreload0
event entity @s[hasitem=[{item=krep:mag357,quantity=1},{item=krep:ammoboxc,quantity=0}]] deaglegreload1
event entity @s[hasitem=[{item=krep:mag357,quantity=2},{item=krep:ammoboxc,quantity=0}]] deaglegreload2
event entity @s[hasitem=[{item=krep:mag357,quantity=3},{item=krep:ammoboxc,quantity=0}]] deaglegreload3
event entity @s[hasitem=[{item=krep:mag357,quantity=4},{item=krep:ammoboxc,quantity=0}]] deaglegreload4
event entity @s[hasitem=[{item=krep:mag357,quantity=5},{item=krep:ammoboxc,quantity=0}]] deaglegreload5
event entity @s[hasitem=[{item=krep:mag357,quantity=6},{item=krep:ammoboxc,quantity=0}]] deaglegreload6
event entity @s[hasitem=[{item=krep:mag357,quantity=7},{item=krep:ammoboxc,quantity=0}]] deaglegreload7
event entity @s[hasitem=[{item=krep:mag357,quantity=8},{item=krep:ammoboxc,quantity=0}]] deaglegreload8
event entity @s[hasitem=[{item=krep:mag357,quantity=9},{item=krep:ammoboxc,quantity=0}]] deaglegreload9
event entity @s[hasitem=[{item=krep:mag357,quantity=10},{item=krep:ammoboxc,quantity=0}]] deaglegreload10
event entity @s[hasitem=[{item=krep:mag357,quantity=11},{item=krep:ammoboxc,quantity=0}]] deaglegreload11
event entity @s[hasitem=[{item=krep:mag357,quantity=12},{item=krep:ammoboxc,quantity=0}]] deaglegreload12
event entity @s[hasitem=[{item=krep:mag357,quantity=13},{item=krep:ammoboxc,quantity=0}]] deaglegreload13
event entity @s[hasitem=[{item=krep:mag357,quantity=14},{item=krep:ammoboxc,quantity=0}]] deaglegreload14
event entity @s[hasitem=[{item=krep:mag357,quantity=15},{item=krep:ammoboxc,quantity=0}]] deaglegreload15
event entity @s[hasitem=[{item=krep:mag357,quantity=16},{item=krep:ammoboxc,quantity=0}]] deaglegreload16
event entity @s[hasitem=[{item=krep:mag357,quantity=17..},{item=krep:ammoboxc,quantity=0}]] deaglegreload17
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] deaglegreload17