event entity @s[hasitem=[{item=krep:ae50,quantity=0},{item=krep:ammoboxc,quantity=0}]] deaglereload0
event entity @s[hasitem=[{item=krep:ae50,quantity=1},{item=krep:ammoboxc,quantity=0}]] deaglereload1
event entity @s[hasitem=[{item=krep:ae50,quantity=2},{item=krep:ammoboxc,quantity=0}]] deaglereload2
event entity @s[hasitem=[{item=krep:ae50,quantity=3},{item=krep:ammoboxc,quantity=0}]] deaglereload3
event entity @s[hasitem=[{item=krep:ae50,quantity=4},{item=krep:ammoboxc,quantity=0}]] deaglereload4
event entity @s[hasitem=[{item=krep:ae50,quantity=5},{item=krep:ammoboxc,quantity=0}]] deaglereload5
event entity @s[hasitem=[{item=krep:ae50,quantity=6},{item=krep:ammoboxc,quantity=0}]] deaglereload6
event entity @s[hasitem=[{item=krep:ae50,quantity=7..},{item=krep:ammoboxc,quantity=0}]] deaglereload7
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] deaglereload7