clear @s[m=!c,scores={evolys=74},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 1
clear @s[m=!c,scores={evolys=73},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 2
clear @s[m=!c,scores={evolys=72},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 3
clear @s[m=!c,scores={evolys=71},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 4
clear @s[m=!c,scores={evolys=70},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 5
clear @s[m=!c,scores={evolys=69},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 6
clear @s[m=!c,scores={evolys=68},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 7
clear @s[m=!c,scores={evolys=67},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 8
clear @s[m=!c,scores={evolys=66},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 9
clear @s[m=!c,scores={evolys=65},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 10
clear @s[m=!c,scores={evolys=64},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 11
clear @s[m=!c,scores={evolys=63},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 12
clear @s[m=!c,scores={evolys=62},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 13
clear @s[m=!c,scores={evolys=61},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 14
clear @s[m=!c,scores={evolys=60},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 15
clear @s[m=!c,scores={evolys=59},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 16
clear @s[m=!c,scores={evolys=58},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 17
clear @s[m=!c,scores={evolys=57},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 18
clear @s[m=!c,scores={evolys=56},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 19
clear @s[m=!c,scores={evolys=55},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 20
clear @s[m=!c,scores={evolys=54},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 21
clear @s[m=!c,scores={evolys=53},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 22
clear @s[m=!c,scores={evolys=52},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 23
clear @s[m=!c,scores={evolys=51},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 24
clear @s[m=!c,scores={evolys=50},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 25
clear @s[m=!c,scores={evolys=49},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 26
clear @s[m=!c,scores={evolys=48},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 27
clear @s[m=!c,scores={evolys=47},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 28
clear @s[m=!c,scores={evolys=46},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 29
clear @s[m=!c,scores={evolys=45},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 30
clear @s[m=!c,scores={evolys=44},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 31
clear @s[m=!c,scores={evolys=43},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 32
clear @s[m=!c,scores={evolys=42},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 33
clear @s[m=!c,scores={evolys=41},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 34
clear @s[m=!c,scores={evolys=40},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 35
clear @s[m=!c,scores={evolys=39},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 36
clear @s[m=!c,scores={evolys=38},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 37
clear @s[m=!c,scores={evolys=37},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 38
clear @s[m=!c,scores={evolys=36},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 39
clear @s[m=!c,scores={evolys=35},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 40
clear @s[m=!c,scores={evolys=34},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 41
clear @s[m=!c,scores={evolys=33},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 42
clear @s[m=!c,scores={evolys=32},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 43
clear @s[m=!c,scores={evolys=31},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 44
clear @s[m=!c,scores={evolys=30},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 45
clear @s[m=!c,scores={evolys=29},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 46
clear @s[m=!c,scores={evolys=28},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 47
clear @s[m=!c,scores={evolys=27},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 48
clear @s[m=!c,scores={evolys=26},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 49
clear @s[m=!c,scores={evolys=25},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 50
clear @s[m=!c,scores={evolys=24},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 51
clear @s[m=!c,scores={evolys=23},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 52
clear @s[m=!c,scores={evolys=22},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 53
clear @s[m=!c,scores={evolys=21},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 54
clear @s[m=!c,scores={evolys=20},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 55
clear @s[m=!c,scores={evolys=19},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 56
clear @s[m=!c,scores={evolys=18},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 57
clear @s[m=!c,scores={evolys=17},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 58
clear @s[m=!c,scores={evolys=16},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 59
clear @s[m=!c,scores={evolys=15},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 60
clear @s[m=!c,scores={evolys=14},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 61
clear @s[m=!c,scores={evolys=13},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 62
clear @s[m=!c,scores={evolys=12},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 63
clear @s[m=!c,scores={evolys=11},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 64
clear @s[m=!c,scores={evolys=10},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 65
clear @s[m=!c,scores={evolys=9},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 66
clear @s[m=!c,scores={evolys=8},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 67
clear @s[m=!c,scores={evolys=7},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 68
clear @s[m=!c,scores={evolys=6},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 69
clear @s[m=!c,scores={evolys=5},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 70
clear @s[m=!c,scores={evolys=4},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 71
clear @s[m=!c,scores={evolys=3},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 72
clear @s[m=!c,scores={evolys=2},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 73
clear @s[m=!c,scores={evolys=1},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 74
clear @s[m=!c,scores={evolys=0},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 75