event entity @s[hasitem=[{item=krep:win308,quantity=0},{item=krep:ammoboxc,quantity=0}]] evolysreload0
event entity @s[hasitem=[{item=krep:win308,quantity=1},{item=krep:ammoboxc,quantity=0}]] evolysreload1
event entity @s[hasitem=[{item=krep:win308,quantity=2},{item=krep:ammoboxc,quantity=0}]] evolysreload2
event entity @s[hasitem=[{item=krep:win308,quantity=3},{item=krep:ammoboxc,quantity=0}]] evolysreload3
event entity @s[hasitem=[{item=krep:win308,quantity=4},{item=krep:ammoboxc,quantity=0}]] evolysreload4
event entity @s[hasitem=[{item=krep:win308,quantity=5},{item=krep:ammoboxc,quantity=0}]] evolysreload5
event entity @s[hasitem=[{item=krep:win308,quantity=6},{item=krep:ammoboxc,quantity=0}]] evolysreload6
event entity @s[hasitem=[{item=krep:win308,quantity=7},{item=krep:ammoboxc,quantity=0}]] evolysreload7
event entity @s[hasitem=[{item=krep:win308,quantity=8},{item=krep:ammoboxc,quantity=0}]] evolysreload8
event entity @s[hasitem=[{item=krep:win308,quantity=9},{item=krep:ammoboxc,quantity=0}]] evolysreload9
event entity @s[hasitem=[{item=krep:win308,quantity=10},{item=krep:ammoboxc,quantity=0}]] evolysreload10
event entity @s[hasitem=[{item=krep:win308,quantity=11},{item=krep:ammoboxc,quantity=0}]] evolysreload11
event entity @s[hasitem=[{item=krep:win308,quantity=12},{item=krep:ammoboxc,quantity=0}]] evolysreload12
event entity @s[hasitem=[{item=krep:win308,quantity=13},{item=krep:ammoboxc,quantity=0}]] evolysreload13
event entity @s[hasitem=[{item=krep:win308,quantity=14},{item=krep:ammoboxc,quantity=0}]] evolysreload14
event entity @s[hasitem=[{item=krep:win308,quantity=15},{item=krep:ammoboxc,quantity=0}]] evolysreload15
event entity @s[hasitem=[{item=krep:win308,quantity=16},{item=krep:ammoboxc,quantity=0}]] evolysreload16
event entity @s[hasitem=[{item=krep:win308,quantity=17},{item=krep:ammoboxc,quantity=0}]] evolysreload17
event entity @s[hasitem=[{item=krep:win308,quantity=18},{item=krep:ammoboxc,quantity=0}]] evolysreload18
event entity @s[hasitem=[{item=krep:win308,quantity=19},{item=krep:ammoboxc,quantity=0}]] evolysreload19
event entity @s[hasitem=[{item=krep:win308,quantity=20},{item=krep:ammoboxc,quantity=0}]] evolysreload20
event entity @s[hasitem=[{item=krep:win308,quantity=21},{item=krep:ammoboxc,quantity=0}]] evolysreload21
event entity @s[hasitem=[{item=krep:win308,quantity=22},{item=krep:ammoboxc,quantity=0}]] evolysreload22
event entity @s[hasitem=[{item=krep:win308,quantity=23},{item=krep:ammoboxc,quantity=0}]] evolysreload23
event entity @s[hasitem=[{item=krep:win308,quantity=24},{item=krep:ammoboxc,quantity=0}]] evolysreload24
event entity @s[hasitem=[{item=krep:win308,quantity=25},{item=krep:ammoboxc,quantity=0}]] evolysreload25
event entity @s[hasitem=[{item=krep:win308,quantity=26},{item=krep:ammoboxc,quantity=0}]] evolysreload26
event entity @s[hasitem=[{item=krep:win308,quantity=27},{item=krep:ammoboxc,quantity=0}]] evolysreload27
event entity @s[hasitem=[{item=krep:win308,quantity=28},{item=krep:ammoboxc,quantity=0}]] evolysreload28
event entity @s[hasitem=[{item=krep:win308,quantity=29},{item=krep:ammoboxc,quantity=0}]] evolysreload29
event entity @s[hasitem=[{item=krep:win308,quantity=30},{item=krep:ammoboxc,quantity=0}]] evolysreload30
event entity @s[hasitem=[{item=krep:win308,quantity=31},{item=krep:ammoboxc,quantity=0}]] evolysreload31
event entity @s[hasitem=[{item=krep:win308,quantity=32},{item=krep:ammoboxc,quantity=0}]] evolysreload32
event entity @s[hasitem=[{item=krep:win308,quantity=33},{item=krep:ammoboxc,quantity=0}]] evolysreload33
event entity @s[hasitem=[{item=krep:win308,quantity=34},{item=krep:ammoboxc,quantity=0}]] evolysreload34
event entity @s[hasitem=[{item=krep:win308,quantity=35},{item=krep:ammoboxc,quantity=0}]] evolysreload35
event entity @s[hasitem=[{item=krep:win308,quantity=36},{item=krep:ammoboxc,quantity=0}]] evolysreload36
event entity @s[hasitem=[{item=krep:win308,quantity=37},{item=krep:ammoboxc,quantity=0}]] evolysreload37
event entity @s[hasitem=[{item=krep:win308,quantity=38},{item=krep:ammoboxc,quantity=0}]] evolysreload38
event entity @s[hasitem=[{item=krep:win308,quantity=39},{item=krep:ammoboxc,quantity=0}]] evolysreload39
event entity @s[hasitem=[{item=krep:win308,quantity=40},{item=krep:ammoboxc,quantity=0}]] evolysreload40
event entity @s[hasitem=[{item=krep:win308,quantity=41},{item=krep:ammoboxc,quantity=0}]] evolysreload41
event entity @s[hasitem=[{item=krep:win308,quantity=42},{item=krep:ammoboxc,quantity=0}]] evolysreload42
event entity @s[hasitem=[{item=krep:win308,quantity=43},{item=krep:ammoboxc,quantity=0}]] evolysreload43
event entity @s[hasitem=[{item=krep:win308,quantity=44},{item=krep:ammoboxc,quantity=0}]] evolysreload44
event entity @s[hasitem=[{item=krep:win308,quantity=45},{item=krep:ammoboxc,quantity=0}]] evolysreload45
event entity @s[hasitem=[{item=krep:win308,quantity=46},{item=krep:ammoboxc,quantity=0}]] evolysreload46
event entity @s[hasitem=[{item=krep:win308,quantity=47},{item=krep:ammoboxc,quantity=0}]] evolysreload47
event entity @s[hasitem=[{item=krep:win308,quantity=48},{item=krep:ammoboxc,quantity=0}]] evolysreload48
event entity @s[hasitem=[{item=krep:win308,quantity=49},{item=krep:ammoboxc,quantity=0}]] evolysreload49
event entity @s[hasitem=[{item=krep:win308,quantity=50},{item=krep:ammoboxc,quantity=0}]] evolysreload50
event entity @s[hasitem=[{item=krep:win308,quantity=51},{item=krep:ammoboxc,quantity=0}]] evolysreload51
event entity @s[hasitem=[{item=krep:win308,quantity=52},{item=krep:ammoboxc,quantity=0}]] evolysreload52
event entity @s[hasitem=[{item=krep:win308,quantity=53},{item=krep:ammoboxc,quantity=0}]] evolysreload53
event entity @s[hasitem=[{item=krep:win308,quantity=54},{item=krep:ammoboxc,quantity=0}]] evolysreload54
event entity @s[hasitem=[{item=krep:win308,quantity=55},{item=krep:ammoboxc,quantity=0}]] evolysreload55
event entity @s[hasitem=[{item=krep:win308,quantity=56},{item=krep:ammoboxc,quantity=0}]] evolysreload56
event entity @s[hasitem=[{item=krep:win308,quantity=57},{item=krep:ammoboxc,quantity=0}]] evolysreload57
event entity @s[hasitem=[{item=krep:win308,quantity=58},{item=krep:ammoboxc,quantity=0}]] evolysreload58
event entity @s[hasitem=[{item=krep:win308,quantity=59},{item=krep:ammoboxc,quantity=0}]] evolysreload59
event entity @s[hasitem=[{item=krep:win308,quantity=60},{item=krep:ammoboxc,quantity=0}]] evolysreload60
event entity @s[hasitem=[{item=krep:win308,quantity=61},{item=krep:ammoboxc,quantity=0}]] evolysreload61
event entity @s[hasitem=[{item=krep:win308,quantity=62},{item=krep:ammoboxc,quantity=0}]] evolysreload62
event entity @s[hasitem=[{item=krep:win308,quantity=63},{item=krep:ammoboxc,quantity=0}]] evolysreload63
event entity @s[hasitem=[{item=krep:win308,quantity=64},{item=krep:ammoboxc,quantity=0}]] evolysreload64
event entity @s[hasitem=[{item=krep:win308,quantity=65},{item=krep:ammoboxc,quantity=0}]] evolysreload65
event entity @s[hasitem=[{item=krep:win308,quantity=66},{item=krep:ammoboxc,quantity=0}]] evolysreload66
event entity @s[hasitem=[{item=krep:win308,quantity=67},{item=krep:ammoboxc,quantity=0}]] evolysreload67
event entity @s[hasitem=[{item=krep:win308,quantity=68},{item=krep:ammoboxc,quantity=0}]] evolysreload68
event entity @s[hasitem=[{item=krep:win308,quantity=69},{item=krep:ammoboxc,quantity=0}]] evolysreload69
event entity @s[hasitem=[{item=krep:win308,quantity=70},{item=krep:ammoboxc,quantity=0}]] evolysreload70
event entity @s[hasitem=[{item=krep:win308,quantity=71},{item=krep:ammoboxc,quantity=0}]] evolysreload71
event entity @s[hasitem=[{item=krep:win308,quantity=72},{item=krep:ammoboxc,quantity=0}]] evolysreload72
event entity @s[hasitem=[{item=krep:win308,quantity=73},{item=krep:ammoboxc,quantity=0}]] evolysreload73
event entity @s[hasitem=[{item=krep:win308,quantity=74},{item=krep:ammoboxc,quantity=0}]] evolysreload74
event entity @s[hasitem=[{item=krep:win308,quantity=75..},{item=krep:ammoboxc,quantity=0}]] evolysreload75
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] evolysreload75