event entity @s[hasitem=[{item=krep:win308,quantity=0},{item=krep:ammoboxc,quantity=0}]] falreload0
event entity @s[hasitem=[{item=krep:win308,quantity=1},{item=krep:ammoboxc,quantity=0}]] falreload1
event entity @s[hasitem=[{item=krep:win308,quantity=2},{item=krep:ammoboxc,quantity=0}]] falreload2
event entity @s[hasitem=[{item=krep:win308,quantity=3},{item=krep:ammoboxc,quantity=0}]] falreload3
event entity @s[hasitem=[{item=krep:win308,quantity=4},{item=krep:ammoboxc,quantity=0}]] falreload4
event entity @s[hasitem=[{item=krep:win308,quantity=5},{item=krep:ammoboxc,quantity=0}]] falreload5
event entity @s[hasitem=[{item=krep:win308,quantity=6},{item=krep:ammoboxc,quantity=0}]] falreload6
event entity @s[hasitem=[{item=krep:win308,quantity=7},{item=krep:ammoboxc,quantity=0}]] falreload7
event entity @s[hasitem=[{item=krep:win308,quantity=8},{item=krep:ammoboxc,quantity=0}]] falreload8
event entity @s[hasitem=[{item=krep:win308,quantity=9},{item=krep:ammoboxc,quantity=0}]] falreload9
event entity @s[hasitem=[{item=krep:win308,quantity=10},{item=krep:ammoboxc,quantity=0}]] falreload10
event entity @s[hasitem=[{item=krep:win308,quantity=11},{item=krep:ammoboxc,quantity=0}]] falreload11
event entity @s[hasitem=[{item=krep:win308,quantity=12},{item=krep:ammoboxc,quantity=0}]] falreload12
event entity @s[hasitem=[{item=krep:win308,quantity=13},{item=krep:ammoboxc,quantity=0}]] falreload13
event entity @s[hasitem=[{item=krep:win308,quantity=14},{item=krep:ammoboxc,quantity=0}]] falreload14
event entity @s[hasitem=[{item=krep:win308,quantity=15},{item=krep:ammoboxc,quantity=0}]] falreload15
event entity @s[hasitem=[{item=krep:win308,quantity=16},{item=krep:ammoboxc,quantity=0}]] falreload16
event entity @s[hasitem=[{item=krep:win308,quantity=17},{item=krep:ammoboxc,quantity=0}]] falreload17
event entity @s[hasitem=[{item=krep:win308,quantity=18},{item=krep:ammoboxc,quantity=0}]] falreload18
event entity @s[hasitem=[{item=krep:win308,quantity=19},{item=krep:ammoboxc,quantity=0}]] falreload19
event entity @s[hasitem=[{item=krep:win308,quantity=20..},{item=krep:ammoboxc,quantity=0}]] falreload20
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] falreload20