event entity @s[hasitem=[{item=krep:mm9,quantity=0},{item=krep:ammoboxc,quantity=0}]] g18reload0
event entity @s[hasitem=[{item=krep:mm9,quantity=1},{item=krep:ammoboxc,quantity=0}]] g18reload1
event entity @s[hasitem=[{item=krep:mm9,quantity=2},{item=krep:ammoboxc,quantity=0}]] g18reload2
event entity @s[hasitem=[{item=krep:mm9,quantity=3},{item=krep:ammoboxc,quantity=0}]] g18reload3
event entity @s[hasitem=[{item=krep:mm9,quantity=4},{item=krep:ammoboxc,quantity=0}]] g18reload4
event entity @s[hasitem=[{item=krep:mm9,quantity=5},{item=krep:ammoboxc,quantity=0}]] g18reload5
event entity @s[hasitem=[{item=krep:mm9,quantity=6},{item=krep:ammoboxc,quantity=0}]] g18reload6
event entity @s[hasitem=[{item=krep:mm9,quantity=7},{item=krep:ammoboxc,quantity=0}]] g18reload7
event entity @s[hasitem=[{item=krep:mm9,quantity=8},{item=krep:ammoboxc,quantity=0}]] g18reload8
event entity @s[hasitem=[{item=krep:mm9,quantity=9},{item=krep:ammoboxc,quantity=0}]] g18reload9
event entity @s[hasitem=[{item=krep:mm9,quantity=10},{item=krep:ammoboxc,quantity=0}]] g18reload10
event entity @s[hasitem=[{item=krep:mm9,quantity=11},{item=krep:ammoboxc,quantity=0}]] g18reload11
event entity @s[hasitem=[{item=krep:mm9,quantity=12},{item=krep:ammoboxc,quantity=0}]] g18reload12
event entity @s[hasitem=[{item=krep:mm9,quantity=13},{item=krep:ammoboxc,quantity=0}]] g18reload13
event entity @s[hasitem=[{item=krep:mm9,quantity=14},{item=krep:ammoboxc,quantity=0}]] g18reload14
event entity @s[hasitem=[{item=krep:mm9,quantity=15},{item=krep:ammoboxc,quantity=0}]] g18reload15
event entity @s[hasitem=[{item=krep:mm9,quantity=16},{item=krep:ammoboxc,quantity=0}]] g18reload16
event entity @s[hasitem=[{item=krep:mm9,quantity=17..},{item=krep:ammoboxc,quantity=0}]] g18reload17
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] g18reload17