event entity @s[hasitem=[{item=krep:m885,quantity=0},{item=krep:ammoboxc,quantity=0}]] g36reload0
event entity @s[hasitem=[{item=krep:m885,quantity=1},{item=krep:ammoboxc,quantity=0}]] g36reload1
event entity @s[hasitem=[{item=krep:m885,quantity=2},{item=krep:ammoboxc,quantity=0}]] g36reload2
event entity @s[hasitem=[{item=krep:m885,quantity=3},{item=krep:ammoboxc,quantity=0}]] g36reload3
event entity @s[hasitem=[{item=krep:m885,quantity=4},{item=krep:ammoboxc,quantity=0}]] g36reload4
event entity @s[hasitem=[{item=krep:m885,quantity=5},{item=krep:ammoboxc,quantity=0}]] g36reload5
event entity @s[hasitem=[{item=krep:m885,quantity=6},{item=krep:ammoboxc,quantity=0}]] g36reload6
event entity @s[hasitem=[{item=krep:m885,quantity=7},{item=krep:ammoboxc,quantity=0}]] g36reload7
event entity @s[hasitem=[{item=krep:m885,quantity=8},{item=krep:ammoboxc,quantity=0}]] g36reload8
event entity @s[hasitem=[{item=krep:m885,quantity=9},{item=krep:ammoboxc,quantity=0}]] g36reload9
event entity @s[hasitem=[{item=krep:m885,quantity=10},{item=krep:ammoboxc,quantity=0}]] g36reload10
event entity @s[hasitem=[{item=krep:m885,quantity=11},{item=krep:ammoboxc,quantity=0}]] g36reload11
event entity @s[hasitem=[{item=krep:m885,quantity=12},{item=krep:ammoboxc,quantity=0}]] g36reload12
event entity @s[hasitem=[{item=krep:m885,quantity=13},{item=krep:ammoboxc,quantity=0}]] g36reload13
event entity @s[hasitem=[{item=krep:m885,quantity=14},{item=krep:ammoboxc,quantity=0}]] g36reload14
event entity @s[hasitem=[{item=krep:m885,quantity=15},{item=krep:ammoboxc,quantity=0}]] g36reload15
event entity @s[hasitem=[{item=krep:m885,quantity=16},{item=krep:ammoboxc,quantity=0}]] g36reload16
event entity @s[hasitem=[{item=krep:m885,quantity=17},{item=krep:ammoboxc,quantity=0}]] g36reload17
event entity @s[hasitem=[{item=krep:m885,quantity=18},{item=krep:ammoboxc,quantity=0}]] g36reload18
event entity @s[hasitem=[{item=krep:m885,quantity=19},{item=krep:ammoboxc,quantity=0}]] g36reload19
event entity @s[hasitem=[{item=krep:m885,quantity=20},{item=krep:ammoboxc,quantity=0}]] g36reload20
event entity @s[hasitem=[{item=krep:m885,quantity=21},{item=krep:ammoboxc,quantity=0}]] g36reload21
event entity @s[hasitem=[{item=krep:m885,quantity=22},{item=krep:ammoboxc,quantity=0}]] g36reload22
event entity @s[hasitem=[{item=krep:m885,quantity=23},{item=krep:ammoboxc,quantity=0}]] g36reload23
event entity @s[hasitem=[{item=krep:m885,quantity=24},{item=krep:ammoboxc,quantity=0}]] g36reload24
event entity @s[hasitem=[{item=krep:m885,quantity=25},{item=krep:ammoboxc,quantity=0}]] g36reload25
event entity @s[hasitem=[{item=krep:m885,quantity=26},{item=krep:ammoboxc,quantity=0}]] g36reload26
event entity @s[hasitem=[{item=krep:m885,quantity=27},{item=krep:ammoboxc,quantity=0}]] g36reload27
event entity @s[hasitem=[{item=krep:m885,quantity=28},{item=krep:ammoboxc,quantity=0}]] g36reload28
event entity @s[hasitem=[{item=krep:m885,quantity=29},{item=krep:ammoboxc,quantity=0}]] g36reload29
event entity @s[hasitem=[{item=krep:m885,quantity=30..},{item=krep:ammoboxc,quantity=0}]] g36reload30
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] g36reload30