event entity @s[hasitem=[{item=krep:50bmg,quantity=0},{item=krep:ammoboxc,quantity=0}]] m107reload0
event entity @s[hasitem=[{item=krep:50bmg,quantity=1},{item=krep:ammoboxc,quantity=0}]] m107reload1
event entity @s[hasitem=[{item=krep:50bmg,quantity=2},{item=krep:ammoboxc,quantity=0}]] m107reload2
event entity @s[hasitem=[{item=krep:50bmg,quantity=3},{item=krep:ammoboxc,quantity=0}]] m107reload3
event entity @s[hasitem=[{item=krep:50bmg,quantity=4},{item=krep:ammoboxc,quantity=0}]] m107reload4
event entity @s[hasitem=[{item=krep:50bmg,quantity=5},{item=krep:ammoboxc,quantity=0}]] m107reload5
event entity @s[hasitem=[{item=krep:50bmg,quantity=6},{item=krep:ammoboxc,quantity=0}]] m107reload6
event entity @s[hasitem=[{item=krep:50bmg,quantity=7},{item=krep:ammoboxc,quantity=0}]] m107reload7
event entity @s[hasitem=[{item=krep:50bmg,quantity=8},{item=krep:ammoboxc,quantity=0}]] m107reload8
event entity @s[hasitem=[{item=krep:50bmg,quantity=9},{item=krep:ammoboxc,quantity=0}]] m107reload9
event entity @s[hasitem=[{item=krep:50bmg,quantity=10..},{item=krep:ammoboxc,quantity=0}]] m107reload10
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] m107reload10
