event entity @s[hasitem=[{item=krep:m885,quantity=0},{item=krep:ammoboxc,quantity=0}]] m16a1reload0
event entity @s[hasitem=[{item=krep:m885,quantity=1},{item=krep:ammoboxc,quantity=0}]] m16a1reload1
event entity @s[hasitem=[{item=krep:m885,quantity=2},{item=krep:ammoboxc,quantity=0}]] m16a1reload2
event entity @s[hasitem=[{item=krep:m885,quantity=3},{item=krep:ammoboxc,quantity=0}]] m16a1reload3
event entity @s[hasitem=[{item=krep:m885,quantity=4},{item=krep:ammoboxc,quantity=0}]] m16a1reload4
event entity @s[hasitem=[{item=krep:m885,quantity=5},{item=krep:ammoboxc,quantity=0}]] m16a1reload5
event entity @s[hasitem=[{item=krep:m885,quantity=6},{item=krep:ammoboxc,quantity=0}]] m16a1reload6
event entity @s[hasitem=[{item=krep:m885,quantity=7},{item=krep:ammoboxc,quantity=0}]] m16a1reload7
event entity @s[hasitem=[{item=krep:m885,quantity=8},{item=krep:ammoboxc,quantity=0}]] m16a1reload8
event entity @s[hasitem=[{item=krep:m885,quantity=9},{item=krep:ammoboxc,quantity=0}]] m16a1reload9
event entity @s[hasitem=[{item=krep:m885,quantity=10},{item=krep:ammoboxc,quantity=0}]] m16a1reload10
event entity @s[hasitem=[{item=krep:m885,quantity=11},{item=krep:ammoboxc,quantity=0}]] m16a1reload11
event entity @s[hasitem=[{item=krep:m885,quantity=12},{item=krep:ammoboxc,quantity=0}]] m16a1reload12
event entity @s[hasitem=[{item=krep:m885,quantity=13},{item=krep:ammoboxc,quantity=0}]] m16a1reload13
event entity @s[hasitem=[{item=krep:m885,quantity=14},{item=krep:ammoboxc,quantity=0}]] m16a1reload14
event entity @s[hasitem=[{item=krep:m885,quantity=15},{item=krep:ammoboxc,quantity=0}]] m16a1reload15
event entity @s[hasitem=[{item=krep:m885,quantity=16},{item=krep:ammoboxc,quantity=0}]] m16a1reload16
event entity @s[hasitem=[{item=krep:m885,quantity=17},{item=krep:ammoboxc,quantity=0}]] m16a1reload17
event entity @s[hasitem=[{item=krep:m885,quantity=18},{item=krep:ammoboxc,quantity=0}]] m16a1reload18
event entity @s[hasitem=[{item=krep:m885,quantity=19},{item=krep:ammoboxc,quantity=0}]] m16a1reload19
event entity @s[hasitem=[{item=krep:m885,quantity=20..},{item=krep:ammoboxc,quantity=0}]] m16a1reload20
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] m16a1reload20