event entity @s[hasitem=[{item=krep:m885,quantity=0},{item=krep:ammoboxc,quantity=0}]] m16reload0
event entity @s[hasitem=[{item=krep:m885,quantity=1},{item=krep:ammoboxc,quantity=0}]] m16reload1
event entity @s[hasitem=[{item=krep:m885,quantity=2},{item=krep:ammoboxc,quantity=0}]] m16reload2
event entity @s[hasitem=[{item=krep:m885,quantity=3},{item=krep:ammoboxc,quantity=0}]] m16reload3
event entity @s[hasitem=[{item=krep:m885,quantity=4},{item=krep:ammoboxc,quantity=0}]] m16reload4
event entity @s[hasitem=[{item=krep:m885,quantity=5},{item=krep:ammoboxc,quantity=0}]] m16reload5
event entity @s[hasitem=[{item=krep:m885,quantity=6},{item=krep:ammoboxc,quantity=0}]] m16reload6
event entity @s[hasitem=[{item=krep:m885,quantity=7},{item=krep:ammoboxc,quantity=0}]] m16reload7
event entity @s[hasitem=[{item=krep:m885,quantity=8},{item=krep:ammoboxc,quantity=0}]] m16reload8
event entity @s[hasitem=[{item=krep:m885,quantity=9},{item=krep:ammoboxc,quantity=0}]] m16reload9
event entity @s[hasitem=[{item=krep:m885,quantity=10},{item=krep:ammoboxc,quantity=0}]] m16reload10
event entity @s[hasitem=[{item=krep:m885,quantity=11},{item=krep:ammoboxc,quantity=0}]] m16reload11
event entity @s[hasitem=[{item=krep:m885,quantity=12},{item=krep:ammoboxc,quantity=0}]] m16reload12
event entity @s[hasitem=[{item=krep:m885,quantity=13},{item=krep:ammoboxc,quantity=0}]] m16reload13
event entity @s[hasitem=[{item=krep:m885,quantity=14},{item=krep:ammoboxc,quantity=0}]] m16reload14
event entity @s[hasitem=[{item=krep:m885,quantity=15},{item=krep:ammoboxc,quantity=0}]] m16reload15
event entity @s[hasitem=[{item=krep:m885,quantity=16},{item=krep:ammoboxc,quantity=0}]] m16reload16
event entity @s[hasitem=[{item=krep:m885,quantity=17},{item=krep:ammoboxc,quantity=0}]] m16reload17
event entity @s[hasitem=[{item=krep:m885,quantity=18},{item=krep:ammoboxc,quantity=0}]] m16reload18
event entity @s[hasitem=[{item=krep:m885,quantity=19},{item=krep:ammoboxc,quantity=0}]] m16reload19
event entity @s[hasitem=[{item=krep:m885,quantity=20},{item=krep:ammoboxc,quantity=0}]] m16reload20
event entity @s[hasitem=[{item=krep:m885,quantity=21},{item=krep:ammoboxc,quantity=0}]] m16reload21
event entity @s[hasitem=[{item=krep:m885,quantity=22},{item=krep:ammoboxc,quantity=0}]] m16reload22
event entity @s[hasitem=[{item=krep:m885,quantity=23},{item=krep:ammoboxc,quantity=0}]] m16reload23
event entity @s[hasitem=[{item=krep:m885,quantity=24},{item=krep:ammoboxc,quantity=0}]] m16reload24
event entity @s[hasitem=[{item=krep:m885,quantity=25},{item=krep:ammoboxc,quantity=0}]] m16reload25
event entity @s[hasitem=[{item=krep:m885,quantity=26},{item=krep:ammoboxc,quantity=0}]] m16reload26
event entity @s[hasitem=[{item=krep:m885,quantity=27},{item=krep:ammoboxc,quantity=0}]] m16reload27
event entity @s[hasitem=[{item=krep:m885,quantity=28},{item=krep:ammoboxc,quantity=0}]] m16reload28
event entity @s[hasitem=[{item=krep:m885,quantity=29},{item=krep:ammoboxc,quantity=0}]] m16reload29
event entity @s[hasitem=[{item=krep:m885,quantity=30..},{item=krep:ammoboxc,quantity=0}]] m16reload30
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] m16reload30