event entity @s[hasitem=[{item=krep:acp45,quantity=0},{item=krep:ammoboxc,quantity=0}]] m1911reload0
event entity @s[hasitem=[{item=krep:acp45,quantity=1},{item=krep:ammoboxc,quantity=0}]] m1911reload1
event entity @s[hasitem=[{item=krep:acp45,quantity=2},{item=krep:ammoboxc,quantity=0}]] m1911reload2
event entity @s[hasitem=[{item=krep:acp45,quantity=3},{item=krep:ammoboxc,quantity=0}]] m1911reload3
event entity @s[hasitem=[{item=krep:acp45,quantity=4},{item=krep:ammoboxc,quantity=0}]] m1911reload4
event entity @s[hasitem=[{item=krep:acp45,quantity=5},{item=krep:ammoboxc,quantity=0}]] m1911reload5
event entity @s[hasitem=[{item=krep:acp45,quantity=6},{item=krep:ammoboxc,quantity=0}]] m1911reload6
event entity @s[hasitem=[{item=krep:acp45,quantity=7..},{item=krep:ammoboxc,quantity=0}]] m1911reload7
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] m1911reload7