event entity @s[hasitem=[{item=krep:mm9,quantity=0},{item=krep:ammoboxc,quantity=0}]] m9a4reload0
event entity @s[hasitem=[{item=krep:mm9,quantity=1},{item=krep:ammoboxc,quantity=0}]] m9a4reload1
event entity @s[hasitem=[{item=krep:mm9,quantity=2},{item=krep:ammoboxc,quantity=0}]] m9a4reload2
event entity @s[hasitem=[{item=krep:mm9,quantity=3},{item=krep:ammoboxc,quantity=0}]] m9a4reload3
event entity @s[hasitem=[{item=krep:mm9,quantity=4},{item=krep:ammoboxc,quantity=0}]] m9a4reload4
event entity @s[hasitem=[{item=krep:mm9,quantity=5},{item=krep:ammoboxc,quantity=0}]] m9a4reload5
event entity @s[hasitem=[{item=krep:mm9,quantity=6},{item=krep:ammoboxc,quantity=0}]] m9a4reload6
event entity @s[hasitem=[{item=krep:mm9,quantity=7},{item=krep:ammoboxc,quantity=0}]] m9a4reload7
event entity @s[hasitem=[{item=krep:mm9,quantity=8},{item=krep:ammoboxc,quantity=0}]] m9a4reload8
event entity @s[hasitem=[{item=krep:mm9,quantity=9},{item=krep:ammoboxc,quantity=0}]] m9a4reload9
event entity @s[hasitem=[{item=krep:mm9,quantity=10},{item=krep:ammoboxc,quantity=0}]] m9a4reload10
event entity @s[hasitem=[{item=krep:mm9,quantity=11},{item=krep:ammoboxc,quantity=0}]] m9a4reload11
event entity @s[hasitem=[{item=krep:mm9,quantity=12},{item=krep:ammoboxc,quantity=0}]] m9a4reload12
event entity @s[hasitem=[{item=krep:mm9,quantity=13},{item=krep:ammoboxc,quantity=0}]] m9a4reload13
event entity @s[hasitem=[{item=krep:mm9,quantity=14},{item=krep:ammoboxc,quantity=0}]] m9a4reload14
event entity @s[hasitem=[{item=krep:mm9,quantity=15},{item=krep:ammoboxc,quantity=0}]] m9a4reload15
event entity @s[hasitem=[{item=krep:mm9,quantity=16},{item=krep:ammoboxc,quantity=0}]] m9a4reload16
event entity @s[hasitem=[{item=krep:mm9,quantity=17..},{item=krep:ammoboxc,quantity=0}]] m9a4reload17
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] m9a4reload17