event entity @s[hasitem=[{item=krep:win308,quantity=0},{item=krep:ammoboxc,quantity=0}]] mk14reload0
event entity @s[hasitem=[{item=krep:win308,quantity=1},{item=krep:ammoboxc,quantity=0}]] mk14reload1
event entity @s[hasitem=[{item=krep:win308,quantity=2},{item=krep:ammoboxc,quantity=0}]] mk14reload2
event entity @s[hasitem=[{item=krep:win308,quantity=3},{item=krep:ammoboxc,quantity=0}]] mk14reload3
event entity @s[hasitem=[{item=krep:win308,quantity=4},{item=krep:ammoboxc,quantity=0}]] mk14reload4
event entity @s[hasitem=[{item=krep:win308,quantity=5},{item=krep:ammoboxc,quantity=0}]] mk14reload5
event entity @s[hasitem=[{item=krep:win308,quantity=6},{item=krep:ammoboxc,quantity=0}]] mk14reload6
event entity @s[hasitem=[{item=krep:win308,quantity=7},{item=krep:ammoboxc,quantity=0}]] mk14reload7
event entity @s[hasitem=[{item=krep:win308,quantity=8},{item=krep:ammoboxc,quantity=0}]] mk14reload8
event entity @s[hasitem=[{item=krep:win308,quantity=9},{item=krep:ammoboxc,quantity=0}]] mk14reload9
event entity @s[hasitem=[{item=krep:win308,quantity=10},{item=krep:ammoboxc,quantity=0}]] mk14reload10
event entity @s[hasitem=[{item=krep:win308,quantity=11},{item=krep:ammoboxc,quantity=0}]] mk14reload11
event entity @s[hasitem=[{item=krep:win308,quantity=12},{item=krep:ammoboxc,quantity=0}]] mk14reload12
event entity @s[hasitem=[{item=krep:win308,quantity=13},{item=krep:ammoboxc,quantity=0}]] mk14reload13
event entity @s[hasitem=[{item=krep:win308,quantity=14},{item=krep:ammoboxc,quantity=0}]] mk14reload14
event entity @s[hasitem=[{item=krep:win308,quantity=15},{item=krep:ammoboxc,quantity=0}]] mk14reload15
event entity @s[hasitem=[{item=krep:win308,quantity=16},{item=krep:ammoboxc,quantity=0}]] mk14reload16
event entity @s[hasitem=[{item=krep:win308,quantity=17},{item=krep:ammoboxc,quantity=0}]] mk14reload17
event entity @s[hasitem=[{item=krep:win308,quantity=18},{item=krep:ammoboxc,quantity=0}]] mk14reload18
event entity @s[hasitem=[{item=krep:win308,quantity=19},{item=krep:ammoboxc,quantity=0}]] mk14reload19
event entity @s[hasitem=[{item=krep:win308,quantity=20..},{item=krep:ammoboxc,quantity=0}]] mk14reload20
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] mk14reload20