event entity @s[hasitem=[{item=krep:acp45,quantity=0},{item=krep:ammoboxc,quantity=0}]] mk23reload0
event entity @s[hasitem=[{item=krep:acp45,quantity=1},{item=krep:ammoboxc,quantity=0}]] mk23reload1
event entity @s[hasitem=[{item=krep:acp45,quantity=2},{item=krep:ammoboxc,quantity=0}]] mk23reload2
event entity @s[hasitem=[{item=krep:acp45,quantity=3},{item=krep:ammoboxc,quantity=0}]] mk23reload3
event entity @s[hasitem=[{item=krep:acp45,quantity=4},{item=krep:ammoboxc,quantity=0}]] mk23reload4
event entity @s[hasitem=[{item=krep:acp45,quantity=5},{item=krep:ammoboxc,quantity=0}]] mk23reload5
event entity @s[hasitem=[{item=krep:acp45,quantity=6},{item=krep:ammoboxc,quantity=0}]] mk23reload6
event entity @s[hasitem=[{item=krep:acp45,quantity=7},{item=krep:ammoboxc,quantity=0}]] mk23reload7
event entity @s[hasitem=[{item=krep:acp45,quantity=8},{item=krep:ammoboxc,quantity=0}]] mk23reload8
event entity @s[hasitem=[{item=krep:acp45,quantity=9},{item=krep:ammoboxc,quantity=0}]] mk23reload9
event entity @s[hasitem=[{item=krep:acp45,quantity=10},{item=krep:ammoboxc,quantity=0}]] mk23reload10
event entity @s[hasitem=[{item=krep:acp45,quantity=11},{item=krep:ammoboxc,quantity=0}]] mk23reload11
event entity @s[hasitem=[{item=krep:acp45,quantity=12..},{item=krep:ammoboxc,quantity=0}]] mk23reload12
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] mk23reload12