event entity @s[hasitem=[{item=krep:mm9,quantity=0},{item=krep:ammoboxc,quantity=0}]] mp5reload0
event entity @s[hasitem=[{item=krep:mm9,quantity=1},{item=krep:ammoboxc,quantity=0}]] mp5reload1
event entity @s[hasitem=[{item=krep:mm9,quantity=2},{item=krep:ammoboxc,quantity=0}]] mp5reload2
event entity @s[hasitem=[{item=krep:mm9,quantity=3},{item=krep:ammoboxc,quantity=0}]] mp5reload3
event entity @s[hasitem=[{item=krep:mm9,quantity=4},{item=krep:ammoboxc,quantity=0}]] mp5reload4
event entity @s[hasitem=[{item=krep:mm9,quantity=5},{item=krep:ammoboxc,quantity=0}]] mp5reload5
event entity @s[hasitem=[{item=krep:mm9,quantity=6},{item=krep:ammoboxc,quantity=0}]] mp5reload6
event entity @s[hasitem=[{item=krep:mm9,quantity=7},{item=krep:ammoboxc,quantity=0}]] mp5reload7
event entity @s[hasitem=[{item=krep:mm9,quantity=8},{item=krep:ammoboxc,quantity=0}]] mp5reload8
event entity @s[hasitem=[{item=krep:mm9,quantity=9},{item=krep:ammoboxc,quantity=0}]] mp5reload9
event entity @s[hasitem=[{item=krep:mm9,quantity=10},{item=krep:ammoboxc,quantity=0}]] mp5reload10
event entity @s[hasitem=[{item=krep:mm9,quantity=11},{item=krep:ammoboxc,quantity=0}]] mp5reload11
event entity @s[hasitem=[{item=krep:mm9,quantity=12},{item=krep:ammoboxc,quantity=0}]] mp5reload12
event entity @s[hasitem=[{item=krep:mm9,quantity=13},{item=krep:ammoboxc,quantity=0}]] mp5reload13
event entity @s[hasitem=[{item=krep:mm9,quantity=14},{item=krep:ammoboxc,quantity=0}]] mp5reload14
event entity @s[hasitem=[{item=krep:mm9,quantity=15},{item=krep:ammoboxc,quantity=0}]] mp5reload15
event entity @s[hasitem=[{item=krep:mm9,quantity=16},{item=krep:ammoboxc,quantity=0}]] mp5reload16
event entity @s[hasitem=[{item=krep:mm9,quantity=17},{item=krep:ammoboxc,quantity=0}]] mp5reload17
event entity @s[hasitem=[{item=krep:mm9,quantity=18},{item=krep:ammoboxc,quantity=0}]] mp5reload18
event entity @s[hasitem=[{item=krep:mm9,quantity=19},{item=krep:ammoboxc,quantity=0}]] mp5reload19
event entity @s[hasitem=[{item=krep:mm9,quantity=20},{item=krep:ammoboxc,quantity=0}]] mp5reload20
event entity @s[hasitem=[{item=krep:mm9,quantity=21},{item=krep:ammoboxc,quantity=0}]] mp5reload21
event entity @s[hasitem=[{item=krep:mm9,quantity=22},{item=krep:ammoboxc,quantity=0}]] mp5reload22
event entity @s[hasitem=[{item=krep:mm9,quantity=23},{item=krep:ammoboxc,quantity=0}]] mp5reload23
event entity @s[hasitem=[{item=krep:mm9,quantity=24},{item=krep:ammoboxc,quantity=0}]] mp5reload24
event entity @s[hasitem=[{item=krep:mm9,quantity=25},{item=krep:ammoboxc,quantity=0}]] mp5reload25
event entity @s[hasitem=[{item=krep:mm9,quantity=26},{item=krep:ammoboxc,quantity=0}]] mp5reload26
event entity @s[hasitem=[{item=krep:mm9,quantity=27},{item=krep:ammoboxc,quantity=0}]] mp5reload27
event entity @s[hasitem=[{item=krep:mm9,quantity=28},{item=krep:ammoboxc,quantity=0}]] mp5reload28
event entity @s[hasitem=[{item=krep:mm9,quantity=29},{item=krep:ammoboxc,quantity=0}]] mp5reload29
event entity @s[hasitem=[{item=krep:mm9,quantity=30..},{item=krep:ammoboxc,quantity=0}]] mp5reload30
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] mp5reload30