clear @s[m=!c,scores={mp5=29},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 1
clear @s[m=!c,scores={mp5=28},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 2
clear @s[m=!c,scores={mp5=27},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 3
clear @s[m=!c,scores={mp5=26},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 4
clear @s[m=!c,scores={mp5=25},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 5
clear @s[m=!c,scores={mp5=24},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 6
clear @s[m=!c,scores={mp5=23},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 7
clear @s[m=!c,scores={mp5=22},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 8
clear @s[m=!c,scores={mp5=21},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 9
clear @s[m=!c,scores={mp5=20},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 10
clear @s[m=!c,scores={mp5=19},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 11
clear @s[m=!c,scores={mp5=18},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 12
clear @s[m=!c,scores={mp5=17},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 13
clear @s[m=!c,scores={mp5=16},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 14
clear @s[m=!c,scores={mp5=15},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 15
clear @s[m=!c,scores={mp5=14},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 16
clear @s[m=!c,scores={mp5=13},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 17
clear @s[m=!c,scores={mp5=12},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 18
clear @s[m=!c,scores={mp5=11},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 19
clear @s[m=!c,scores={mp5=10},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 20
clear @s[m=!c,scores={mp5=9},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 21
clear @s[m=!c,scores={mp5=8},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 22
clear @s[m=!c,scores={mp5=7},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 23
clear @s[m=!c,scores={mp5=6},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 24
clear @s[m=!c,scores={mp5=5},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 25
clear @s[m=!c,scores={mp5=4},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 26
clear @s[m=!c,scores={mp5=3},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 27
clear @s[m=!c,scores={mp5=2},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 28
clear @s[m=!c,scores={mp5=1},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 29
clear @s[m=!c,scores={mp5=0},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 30