event entity @s[hasitem=[{item=krep:mm4630,quantity=0},{item=krep:ammoboxc,quantity=0}]] mp7reload0
event entity @s[hasitem=[{item=krep:mm4630,quantity=1},{item=krep:ammoboxc,quantity=0}]] mp7reload1
event entity @s[hasitem=[{item=krep:mm4630,quantity=2},{item=krep:ammoboxc,quantity=0}]] mp7reload2
event entity @s[hasitem=[{item=krep:mm4630,quantity=3},{item=krep:ammoboxc,quantity=0}]] mp7reload3
event entity @s[hasitem=[{item=krep:mm4630,quantity=4},{item=krep:ammoboxc,quantity=0}]] mp7reload4
event entity @s[hasitem=[{item=krep:mm4630,quantity=5},{item=krep:ammoboxc,quantity=0}]] mp7reload5
event entity @s[hasitem=[{item=krep:mm4630,quantity=6},{item=krep:ammoboxc,quantity=0}]] mp7reload6
event entity @s[hasitem=[{item=krep:mm4630,quantity=7},{item=krep:ammoboxc,quantity=0}]] mp7reload7
event entity @s[hasitem=[{item=krep:mm4630,quantity=8},{item=krep:ammoboxc,quantity=0}]] mp7reload8
event entity @s[hasitem=[{item=krep:mm4630,quantity=9},{item=krep:ammoboxc,quantity=0}]] mp7reload9
event entity @s[hasitem=[{item=krep:mm4630,quantity=10},{item=krep:ammoboxc,quantity=0}]] mp7reload10
event entity @s[hasitem=[{item=krep:mm4630,quantity=11},{item=krep:ammoboxc,quantity=0}]] mp7reload11
event entity @s[hasitem=[{item=krep:mm4630,quantity=12},{item=krep:ammoboxc,quantity=0}]] mp7reload12
event entity @s[hasitem=[{item=krep:mm4630,quantity=13},{item=krep:ammoboxc,quantity=0}]] mp7reload13
event entity @s[hasitem=[{item=krep:mm4630,quantity=14},{item=krep:ammoboxc,quantity=0}]] mp7reload14
event entity @s[hasitem=[{item=krep:mm4630,quantity=15},{item=krep:ammoboxc,quantity=0}]] mp7reload15
event entity @s[hasitem=[{item=krep:mm4630,quantity=16},{item=krep:ammoboxc,quantity=0}]] mp7reload16
event entity @s[hasitem=[{item=krep:mm4630,quantity=17},{item=krep:ammoboxc,quantity=0}]] mp7reload17
event entity @s[hasitem=[{item=krep:mm4630,quantity=18},{item=krep:ammoboxc,quantity=0}]] mp7reload18
event entity @s[hasitem=[{item=krep:mm4630,quantity=19},{item=krep:ammoboxc,quantity=0}]] mp7reload19
event entity @s[hasitem=[{item=krep:mm4630,quantity=20},{item=krep:ammoboxc,quantity=0}]] mp7reload20
event entity @s[hasitem=[{item=krep:mm4630,quantity=21},{item=krep:ammoboxc,quantity=0}]] mp7reload21
event entity @s[hasitem=[{item=krep:mm4630,quantity=22},{item=krep:ammoboxc,quantity=0}]] mp7reload22
event entity @s[hasitem=[{item=krep:mm4630,quantity=23},{item=krep:ammoboxc,quantity=0}]] mp7reload23
event entity @s[hasitem=[{item=krep:mm4630,quantity=24},{item=krep:ammoboxc,quantity=0}]] mp7reload24
event entity @s[hasitem=[{item=krep:mm4630,quantity=25},{item=krep:ammoboxc,quantity=0}]] mp7reload25
event entity @s[hasitem=[{item=krep:mm4630,quantity=26},{item=krep:ammoboxc,quantity=0}]] mp7reload26
event entity @s[hasitem=[{item=krep:mm4630,quantity=27},{item=krep:ammoboxc,quantity=0}]] mp7reload27
event entity @s[hasitem=[{item=krep:mm4630,quantity=28},{item=krep:ammoboxc,quantity=0}]] mp7reload28
event entity @s[hasitem=[{item=krep:mm4630,quantity=29},{item=krep:ammoboxc,quantity=0}]] mp7reload29
event entity @s[hasitem=[{item=krep:mm4630,quantity=30},{item=krep:ammoboxc,quantity=0}]] mp7reload30
event entity @s[hasitem=[{item=krep:mm4630,quantity=31},{item=krep:ammoboxc,quantity=0}]] mp7reload31
event entity @s[hasitem=[{item=krep:mm4630,quantity=32},{item=krep:ammoboxc,quantity=0}]] mp7reload32
event entity @s[hasitem=[{item=krep:mm4630,quantity=33},{item=krep:ammoboxc,quantity=0}]] mp7reload33
event entity @s[hasitem=[{item=krep:mm4630,quantity=34},{item=krep:ammoboxc,quantity=0}]] mp7reload34
event entity @s[hasitem=[{item=krep:mm4630,quantity=35},{item=krep:ammoboxc,quantity=0}]] mp7reload35
event entity @s[hasitem=[{item=krep:mm4630,quantity=36},{item=krep:ammoboxc,quantity=0}]] mp7reload36
event entity @s[hasitem=[{item=krep:mm4630,quantity=37},{item=krep:ammoboxc,quantity=0}]] mp7reload37
event entity @s[hasitem=[{item=krep:mm4630,quantity=38},{item=krep:ammoboxc,quantity=0}]] mp7reload38
event entity @s[hasitem=[{item=krep:mm4630,quantity=39},{item=krep:ammoboxc,quantity=0}]] mp7reload39
event entity @s[hasitem=[{item=krep:mm4630,quantity=40..},{item=krep:ammoboxc,quantity=0}]] mp7reload40
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] mp7reload40