event entity @s[hasitem=[{item=krep:acp45,quantity=0},{item=krep:ammoboxc,quantity=0}]] p320reload0
event entity @s[hasitem=[{item=krep:acp45,quantity=1},{item=krep:ammoboxc,quantity=0}]] p320reload1
event entity @s[hasitem=[{item=krep:acp45,quantity=2},{item=krep:ammoboxc,quantity=0}]] p320reload2
event entity @s[hasitem=[{item=krep:acp45,quantity=3},{item=krep:ammoboxc,quantity=0}]] p320reload3
event entity @s[hasitem=[{item=krep:acp45,quantity=4},{item=krep:ammoboxc,quantity=0}]] p320reload4
event entity @s[hasitem=[{item=krep:acp45,quantity=5},{item=krep:ammoboxc,quantity=0}]] p320reload5
event entity @s[hasitem=[{item=krep:acp45,quantity=6},{item=krep:ammoboxc,quantity=0}]] p320reload6
event entity @s[hasitem=[{item=krep:acp45,quantity=7},{item=krep:ammoboxc,quantity=0}]] p320reload7
event entity @s[hasitem=[{item=krep:acp45,quantity=8},{item=krep:ammoboxc,quantity=0}]] p320reload8
event entity @s[hasitem=[{item=krep:acp45,quantity=9},{item=krep:ammoboxc,quantity=0}]] p320reload9
event entity @s[hasitem=[{item=krep:acp45,quantity=10},{item=krep:ammoboxc,quantity=0}]] p320reload10
event entity @s[hasitem=[{item=krep:acp45,quantity=11},{item=krep:ammoboxc,quantity=0}]] p320reload11
event entity @s[hasitem=[{item=krep:acp45,quantity=12..},{item=krep:ammoboxc,quantity=0}]] p320reload12
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] p320reload12