event entity @s[hasitem=[{item=krep:mm5842,quantity=0},{item=krep:ammoboxc,quantity=0}]] qbz95reload0
event entity @s[hasitem=[{item=krep:mm5842,quantity=1},{item=krep:ammoboxc,quantity=0}]] qbz95reload1
event entity @s[hasitem=[{item=krep:mm5842,quantity=2},{item=krep:ammoboxc,quantity=0}]] qbz95reload2
event entity @s[hasitem=[{item=krep:mm5842,quantity=3},{item=krep:ammoboxc,quantity=0}]] qbz95reload3
event entity @s[hasitem=[{item=krep:mm5842,quantity=4},{item=krep:ammoboxc,quantity=0}]] qbz95reload4
event entity @s[hasitem=[{item=krep:mm5842,quantity=5},{item=krep:ammoboxc,quantity=0}]] qbz95reload5
event entity @s[hasitem=[{item=krep:mm5842,quantity=6},{item=krep:ammoboxc,quantity=0}]] qbz95reload6
event entity @s[hasitem=[{item=krep:mm5842,quantity=7},{item=krep:ammoboxc,quantity=0}]] qbz95reload7
event entity @s[hasitem=[{item=krep:mm5842,quantity=8},{item=krep:ammoboxc,quantity=0}]] qbz95reload8
event entity @s[hasitem=[{item=krep:mm5842,quantity=9},{item=krep:ammoboxc,quantity=0}]] qbz95reload9
event entity @s[hasitem=[{item=krep:mm5842,quantity=10},{item=krep:ammoboxc,quantity=0}]] qbz95reload10
event entity @s[hasitem=[{item=krep:mm5842,quantity=11},{item=krep:ammoboxc,quantity=0}]] qbz95reload11
event entity @s[hasitem=[{item=krep:mm5842,quantity=12},{item=krep:ammoboxc,quantity=0}]] qbz95reload12
event entity @s[hasitem=[{item=krep:mm5842,quantity=13},{item=krep:ammoboxc,quantity=0}]] qbz95reload13
event entity @s[hasitem=[{item=krep:mm5842,quantity=14},{item=krep:ammoboxc,quantity=0}]] qbz95reload14
event entity @s[hasitem=[{item=krep:mm5842,quantity=15},{item=krep:ammoboxc,quantity=0}]] qbz95reload15
event entity @s[hasitem=[{item=krep:mm5842,quantity=16},{item=krep:ammoboxc,quantity=0}]] qbz95reload16
event entity @s[hasitem=[{item=krep:mm5842,quantity=17},{item=krep:ammoboxc,quantity=0}]] qbz95reload17
event entity @s[hasitem=[{item=krep:mm5842,quantity=18},{item=krep:ammoboxc,quantity=0}]] qbz95reload18
event entity @s[hasitem=[{item=krep:mm5842,quantity=19},{item=krep:ammoboxc,quantity=0}]] qbz95reload19
event entity @s[hasitem=[{item=krep:mm5842,quantity=20},{item=krep:ammoboxc,quantity=0}]] qbz95reload20
event entity @s[hasitem=[{item=krep:mm5842,quantity=21},{item=krep:ammoboxc,quantity=0}]] qbz95reload21
event entity @s[hasitem=[{item=krep:mm5842,quantity=22},{item=krep:ammoboxc,quantity=0}]] qbz95reload22
event entity @s[hasitem=[{item=krep:mm5842,quantity=23},{item=krep:ammoboxc,quantity=0}]] qbz95reload23
event entity @s[hasitem=[{item=krep:mm5842,quantity=24},{item=krep:ammoboxc,quantity=0}]] qbz95reload24
event entity @s[hasitem=[{item=krep:mm5842,quantity=25},{item=krep:ammoboxc,quantity=0}]] qbz95reload25
event entity @s[hasitem=[{item=krep:mm5842,quantity=26},{item=krep:ammoboxc,quantity=0}]] qbz95reload26
event entity @s[hasitem=[{item=krep:mm5842,quantity=27},{item=krep:ammoboxc,quantity=0}]] qbz95reload27
event entity @s[hasitem=[{item=krep:mm5842,quantity=28},{item=krep:ammoboxc,quantity=0}]] qbz95reload28
event entity @s[hasitem=[{item=krep:mm5842,quantity=29},{item=krep:ammoboxc,quantity=0}]] qbz95reload29
event entity @s[hasitem=[{item=krep:mm5842,quantity=30..},{item=krep:ammoboxc,quantity=0}]] qbz95reload30
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] qbz95reload30