event entity @s[hasitem=[{item=krep:m43,quantity=0},{item=krep:ammoboxc,quantity=0}]] rpkreload0
event entity @s[hasitem=[{item=krep:m43,quantity=1},{item=krep:ammoboxc,quantity=0}]] rpkreload1
event entity @s[hasitem=[{item=krep:m43,quantity=2},{item=krep:ammoboxc,quantity=0}]] rpkreload2
event entity @s[hasitem=[{item=krep:m43,quantity=3},{item=krep:ammoboxc,quantity=0}]] rpkreload3
event entity @s[hasitem=[{item=krep:m43,quantity=4},{item=krep:ammoboxc,quantity=0}]] rpkreload4
event entity @s[hasitem=[{item=krep:m43,quantity=5},{item=krep:ammoboxc,quantity=0}]] rpkreload5
event entity @s[hasitem=[{item=krep:m43,quantity=6},{item=krep:ammoboxc,quantity=0}]] rpkreload6
event entity @s[hasitem=[{item=krep:m43,quantity=7},{item=krep:ammoboxc,quantity=0}]] rpkreload7
event entity @s[hasitem=[{item=krep:m43,quantity=8},{item=krep:ammoboxc,quantity=0}]] rpkreload8
event entity @s[hasitem=[{item=krep:m43,quantity=9},{item=krep:ammoboxc,quantity=0}]] rpkreload9
event entity @s[hasitem=[{item=krep:m43,quantity=10},{item=krep:ammoboxc,quantity=0}]] rpkreload10
event entity @s[hasitem=[{item=krep:m43,quantity=11},{item=krep:ammoboxc,quantity=0}]] rpkreload11
event entity @s[hasitem=[{item=krep:m43,quantity=12},{item=krep:ammoboxc,quantity=0}]] rpkreload12
event entity @s[hasitem=[{item=krep:m43,quantity=13},{item=krep:ammoboxc,quantity=0}]] rpkreload13
event entity @s[hasitem=[{item=krep:m43,quantity=14},{item=krep:ammoboxc,quantity=0}]] rpkreload14
event entity @s[hasitem=[{item=krep:m43,quantity=15},{item=krep:ammoboxc,quantity=0}]] rpkreload15
event entity @s[hasitem=[{item=krep:m43,quantity=16},{item=krep:ammoboxc,quantity=0}]] rpkreload16
event entity @s[hasitem=[{item=krep:m43,quantity=17},{item=krep:ammoboxc,quantity=0}]] rpkreload17
event entity @s[hasitem=[{item=krep:m43,quantity=18},{item=krep:ammoboxc,quantity=0}]] rpkreload18
event entity @s[hasitem=[{item=krep:m43,quantity=19},{item=krep:ammoboxc,quantity=0}]] rpkreload19
event entity @s[hasitem=[{item=krep:m43,quantity=20},{item=krep:ammoboxc,quantity=0}]] rpkreload20
event entity @s[hasitem=[{item=krep:m43,quantity=21},{item=krep:ammoboxc,quantity=0}]] rpkreload21
event entity @s[hasitem=[{item=krep:m43,quantity=22},{item=krep:ammoboxc,quantity=0}]] rpkreload22
event entity @s[hasitem=[{item=krep:m43,quantity=23},{item=krep:ammoboxc,quantity=0}]] rpkreload23
event entity @s[hasitem=[{item=krep:m43,quantity=24},{item=krep:ammoboxc,quantity=0}]] rpkreload24
event entity @s[hasitem=[{item=krep:m43,quantity=25},{item=krep:ammoboxc,quantity=0}]] rpkreload25
event entity @s[hasitem=[{item=krep:m43,quantity=26},{item=krep:ammoboxc,quantity=0}]] rpkreload26
event entity @s[hasitem=[{item=krep:m43,quantity=27},{item=krep:ammoboxc,quantity=0}]] rpkreload27
event entity @s[hasitem=[{item=krep:m43,quantity=28},{item=krep:ammoboxc,quantity=0}]] rpkreload28
event entity @s[hasitem=[{item=krep:m43,quantity=29},{item=krep:ammoboxc,quantity=0}]] rpkreload29
event entity @s[hasitem=[{item=krep:m43,quantity=30},{item=krep:ammoboxc,quantity=0}]] rpkreload30
event entity @s[hasitem=[{item=krep:m43,quantity=31},{item=krep:ammoboxc,quantity=0}]] rpkreload31
event entity @s[hasitem=[{item=krep:m43,quantity=32},{item=krep:ammoboxc,quantity=0}]] rpkreload32
event entity @s[hasitem=[{item=krep:m43,quantity=33},{item=krep:ammoboxc,quantity=0}]] rpkreload33
event entity @s[hasitem=[{item=krep:m43,quantity=34},{item=krep:ammoboxc,quantity=0}]] rpkreload34
event entity @s[hasitem=[{item=krep:m43,quantity=35},{item=krep:ammoboxc,quantity=0}]] rpkreload35
event entity @s[hasitem=[{item=krep:m43,quantity=36},{item=krep:ammoboxc,quantity=0}]] rpkreload36
event entity @s[hasitem=[{item=krep:m43,quantity=37},{item=krep:ammoboxc,quantity=0}]] rpkreload37
event entity @s[hasitem=[{item=krep:m43,quantity=38},{item=krep:ammoboxc,quantity=0}]] rpkreload38
event entity @s[hasitem=[{item=krep:m43,quantity=39},{item=krep:ammoboxc,quantity=0}]] rpkreload39
event entity @s[hasitem=[{item=krep:m43,quantity=40..},{item=krep:ammoboxc,quantity=0}]] rpkreload40
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] rpkreload40