clear @s[m=!c,scores={rpk=39},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 1
clear @s[m=!c,scores={rpk=38},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 2
clear @s[m=!c,scores={rpk=37},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 3
clear @s[m=!c,scores={rpk=36},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 4
clear @s[m=!c,scores={rpk=35},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 5
clear @s[m=!c,scores={rpk=34},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 6
clear @s[m=!c,scores={rpk=33},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 7
clear @s[m=!c,scores={rpk=32},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 8
clear @s[m=!c,scores={rpk=31},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 9
clear @s[m=!c,scores={rpk=30},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 10
clear @s[m=!c,scores={rpk=29},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 11
clear @s[m=!c,scores={rpk=28},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 12
clear @s[m=!c,scores={rpk=27},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 13
clear @s[m=!c,scores={rpk=26},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 14
clear @s[m=!c,scores={rpk=25},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 15
clear @s[m=!c,scores={rpk=24},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 16
clear @s[m=!c,scores={rpk=23},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 17
clear @s[m=!c,scores={rpk=22},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 18
clear @s[m=!c,scores={rpk=21},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 19
clear @s[m=!c,scores={rpk=20},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 20
clear @s[m=!c,scores={rpk=19},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 21
clear @s[m=!c,scores={rpk=18},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 22
clear @s[m=!c,scores={rpk=17},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 23
clear @s[m=!c,scores={rpk=16},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 24
clear @s[m=!c,scores={rpk=15},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 25
clear @s[m=!c,scores={rpk=14},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 26
clear @s[m=!c,scores={rpk=13},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 27
clear @s[m=!c,scores={rpk=12},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 28
clear @s[m=!c,scores={rpk=11},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 29
clear @s[m=!c,scores={rpk=10},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 30
clear @s[m=!c,scores={rpk=9},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 31
clear @s[m=!c,scores={rpk=8},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 32
clear @s[m=!c,scores={rpk=7},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 33
clear @s[m=!c,scores={rpk=6},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 34
clear @s[m=!c,scores={rpk=5},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 35
clear @s[m=!c,scores={rpk=4},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 36
clear @s[m=!c,scores={rpk=3},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 37
clear @s[m=!c,scores={rpk=2},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 38
clear @s[m=!c,scores={rpk=1},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 39
clear @s[m=!c,scores={rpk=0},hasitem={item=krep:ammoboxc,quantity=0}] krep:m43 0 40