clear @s[m=!c,scores={scarh=19},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 1
clear @s[m=!c,scores={scarh=18},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 2
clear @s[m=!c,scores={scarh=17},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 3
clear @s[m=!c,scores={scarh=16},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 4
clear @s[m=!c,scores={scarh=15},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 5
clear @s[m=!c,scores={scarh=14},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 6
clear @s[m=!c,scores={scarh=13},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 7
clear @s[m=!c,scores={scarh=12},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 8
clear @s[m=!c,scores={scarh=11},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 9
clear @s[m=!c,scores={scarh=10},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 10
clear @s[m=!c,scores={scarh=9},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 11
clear @s[m=!c,scores={scarh=8},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 12
clear @s[m=!c,scores={scarh=7},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 13
clear @s[m=!c,scores={scarh=6},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 14
clear @s[m=!c,scores={scarh=5},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 15
clear @s[m=!c,scores={scarh=4},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 16
clear @s[m=!c,scores={scarh=3},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 17
clear @s[m=!c,scores={scarh=1},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 18
clear @s[m=!c,scores={scarh=1},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 19
clear @s[m=!c,scores={scarh=0},hasitem={item=krep:ammoboxc,quantity=0}] krep:win308 0 20