event entity @s[hasitem=[{item=krep:win308,quantity=0},{item=krep:ammoboxc,quantity=0}]] scarhreload0
event entity @s[hasitem=[{item=krep:win308,quantity=1},{item=krep:ammoboxc,quantity=0}]] scarhreload1
event entity @s[hasitem=[{item=krep:win308,quantity=2},{item=krep:ammoboxc,quantity=0}]] scarhreload2
event entity @s[hasitem=[{item=krep:win308,quantity=3},{item=krep:ammoboxc,quantity=0}]] scarhreload3
event entity @s[hasitem=[{item=krep:win308,quantity=4},{item=krep:ammoboxc,quantity=0}]] scarhreload4
event entity @s[hasitem=[{item=krep:win308,quantity=5},{item=krep:ammoboxc,quantity=0}]] scarhreload5
event entity @s[hasitem=[{item=krep:win308,quantity=6},{item=krep:ammoboxc,quantity=0}]] scarhreload6
event entity @s[hasitem=[{item=krep:win308,quantity=7},{item=krep:ammoboxc,quantity=0}]] scarhreload7
event entity @s[hasitem=[{item=krep:win308,quantity=8},{item=krep:ammoboxc,quantity=0}]] scarhreload8
event entity @s[hasitem=[{item=krep:win308,quantity=9},{item=krep:ammoboxc,quantity=0}]] scarhreload9
event entity @s[hasitem=[{item=krep:win308,quantity=10},{item=krep:ammoboxc,quantity=0}]] scarhreload10
event entity @s[hasitem=[{item=krep:win308,quantity=11},{item=krep:ammoboxc,quantity=0}]] scarhreload11
event entity @s[hasitem=[{item=krep:win308,quantity=12},{item=krep:ammoboxc,quantity=0}]] scarhreload12
event entity @s[hasitem=[{item=krep:win308,quantity=13},{item=krep:ammoboxc,quantity=0}]] scarhreload13
event entity @s[hasitem=[{item=krep:win308,quantity=14},{item=krep:ammoboxc,quantity=0}]] scarhreload14
event entity @s[hasitem=[{item=krep:win308,quantity=15},{item=krep:ammoboxc,quantity=0}]] scarhreload15
event entity @s[hasitem=[{item=krep:win308,quantity=16},{item=krep:ammoboxc,quantity=0}]] scarhreload16
event entity @s[hasitem=[{item=krep:win308,quantity=17},{item=krep:ammoboxc,quantity=0}]] scarhreload17
event entity @s[hasitem=[{item=krep:win308,quantity=18},{item=krep:ammoboxc,quantity=0}]] scarhreload18
event entity @s[hasitem=[{item=krep:win308,quantity=19},{item=krep:ammoboxc,quantity=0}]] scarhreload19
event entity @s[hasitem=[{item=krep:win308,quantity=20..},{item=krep:ammoboxc,quantity=0}]] scarhreload20
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] scarhreload20