event entity @s[hasitem=[{item=krep:m885,quantity=0},{item=krep:ammoboxc,quantity=0}]] scarlreload0
event entity @s[hasitem=[{item=krep:m885,quantity=1},{item=krep:ammoboxc,quantity=0}]] scarlreload1
event entity @s[hasitem=[{item=krep:m885,quantity=2},{item=krep:ammoboxc,quantity=0}]] scarlreload2
event entity @s[hasitem=[{item=krep:m885,quantity=3},{item=krep:ammoboxc,quantity=0}]] scarlreload3
event entity @s[hasitem=[{item=krep:m885,quantity=4},{item=krep:ammoboxc,quantity=0}]] scarlreload4
event entity @s[hasitem=[{item=krep:m885,quantity=5},{item=krep:ammoboxc,quantity=0}]] scarlreload5
event entity @s[hasitem=[{item=krep:m885,quantity=6},{item=krep:ammoboxc,quantity=0}]] scarlreload6
event entity @s[hasitem=[{item=krep:m885,quantity=7},{item=krep:ammoboxc,quantity=0}]] scarlreload7
event entity @s[hasitem=[{item=krep:m885,quantity=8},{item=krep:ammoboxc,quantity=0}]] scarlreload8
event entity @s[hasitem=[{item=krep:m885,quantity=9},{item=krep:ammoboxc,quantity=0}]] scarlreload9
event entity @s[hasitem=[{item=krep:m885,quantity=10},{item=krep:ammoboxc,quantity=0}]] scarlreload10
event entity @s[hasitem=[{item=krep:m885,quantity=11},{item=krep:ammoboxc,quantity=0}]] scarlreload11
event entity @s[hasitem=[{item=krep:m885,quantity=12},{item=krep:ammoboxc,quantity=0}]] scarlreload12
event entity @s[hasitem=[{item=krep:m885,quantity=13},{item=krep:ammoboxc,quantity=0}]] scarlreload13
event entity @s[hasitem=[{item=krep:m885,quantity=14},{item=krep:ammoboxc,quantity=0}]] scarlreload14
event entity @s[hasitem=[{item=krep:m885,quantity=15},{item=krep:ammoboxc,quantity=0}]] scarlreload15
event entity @s[hasitem=[{item=krep:m885,quantity=16},{item=krep:ammoboxc,quantity=0}]] scarlreload16
event entity @s[hasitem=[{item=krep:m885,quantity=17},{item=krep:ammoboxc,quantity=0}]] scarlreload17
event entity @s[hasitem=[{item=krep:m885,quantity=18},{item=krep:ammoboxc,quantity=0}]] scarlreload18
event entity @s[hasitem=[{item=krep:m885,quantity=19},{item=krep:ammoboxc,quantity=0}]] scarlreload19
event entity @s[hasitem=[{item=krep:m885,quantity=20},{item=krep:ammoboxc,quantity=0}]] scarlreload20
event entity @s[hasitem=[{item=krep:m885,quantity=21},{item=krep:ammoboxc,quantity=0}]] scarlreload21
event entity @s[hasitem=[{item=krep:m885,quantity=22},{item=krep:ammoboxc,quantity=0}]] scarlreload22
event entity @s[hasitem=[{item=krep:m885,quantity=23},{item=krep:ammoboxc,quantity=0}]] scarlreload23
event entity @s[hasitem=[{item=krep:m885,quantity=24},{item=krep:ammoboxc,quantity=0}]] scarlreload24
event entity @s[hasitem=[{item=krep:m885,quantity=25},{item=krep:ammoboxc,quantity=0}]] scarlreload25
event entity @s[hasitem=[{item=krep:m885,quantity=26},{item=krep:ammoboxc,quantity=0}]] scarlreload26
event entity @s[hasitem=[{item=krep:m885,quantity=27},{item=krep:ammoboxc,quantity=0}]] scarlreload27
event entity @s[hasitem=[{item=krep:m885,quantity=28},{item=krep:ammoboxc,quantity=0}]] scarlreload28
event entity @s[hasitem=[{item=krep:m885,quantity=29},{item=krep:ammoboxc,quantity=0}]] scarlreload29
event entity @s[hasitem=[{item=krep:m885,quantity=30..},{item=krep:ammoboxc,quantity=0}]] scarlreload30
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] scarlreload30