clear @s[m=!c,scores={scarl=29},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 1
clear @s[m=!c,scores={scarl=28},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 2
clear @s[m=!c,scores={scarl=27},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 3
clear @s[m=!c,scores={scarl=26},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 4
clear @s[m=!c,scores={scarl=25},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 5
clear @s[m=!c,scores={scarl=24},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 6
clear @s[m=!c,scores={scarl=23},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 7
clear @s[m=!c,scores={scarl=22},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 8
clear @s[m=!c,scores={scarl=21},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 9
clear @s[m=!c,scores={scarl=20},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 10
clear @s[m=!c,scores={scarl=19},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 11
clear @s[m=!c,scores={scarl=18},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 12
clear @s[m=!c,scores={scarl=17},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 13
clear @s[m=!c,scores={scarl=16},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 14
clear @s[m=!c,scores={scarl=15},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 15
clear @s[m=!c,scores={scarl=14},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 16
clear @s[m=!c,scores={scarl=13},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 17
clear @s[m=!c,scores={scarl=12},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 18
clear @s[m=!c,scores={scarl=11},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 19
clear @s[m=!c,scores={scarl=10},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 20
clear @s[m=!c,scores={scarl=9},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 21
clear @s[m=!c,scores={scarl=8},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 22
clear @s[m=!c,scores={scarl=7},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 23
clear @s[m=!c,scores={scarl=6},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 24
clear @s[m=!c,scores={scarl=5},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 25
clear @s[m=!c,scores={scarl=4},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 26
clear @s[m=!c,scores={scarl=3},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 27
clear @s[m=!c,scores={scarl=2},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 28
clear @s[m=!c,scores={scarl=1},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 29
clear @s[m=!c,scores={scarl=0},hasitem={item=krep:ammoboxc,quantity=0}] krep:m885 0 30