event entity @s[hasitem=[{item=krep:m43,quantity=0},{item=krep:ammoboxc,quantity=0}]] sksreload0
event entity @s[hasitem=[{item=krep:m43,quantity=1},{item=krep:ammoboxc,quantity=0}]] sksreload1
event entity @s[hasitem=[{item=krep:m43,quantity=2},{item=krep:ammoboxc,quantity=0}]] sksreload2
event entity @s[hasitem=[{item=krep:m43,quantity=3},{item=krep:ammoboxc,quantity=0}]] sksreload3
event entity @s[hasitem=[{item=krep:m43,quantity=4},{item=krep:ammoboxc,quantity=0}]] sksreload4
event entity @s[hasitem=[{item=krep:m43,quantity=5},{item=krep:ammoboxc,quantity=0}]] sksreload5
event entity @s[hasitem=[{item=krep:m43,quantity=6},{item=krep:ammoboxc,quantity=0}]] sksreload6
event entity @s[hasitem=[{item=krep:m43,quantity=7},{item=krep:ammoboxc,quantity=0}]] sksreload7
event entity @s[hasitem=[{item=krep:m43,quantity=8},{item=krep:ammoboxc,quantity=0}]] sksreload8
event entity @s[hasitem=[{item=krep:m43,quantity=9},{item=krep:ammoboxc,quantity=0}]] sksreload9
event entity @s[hasitem=[{item=krep:m43,quantity=10..},{item=krep:ammoboxc,quantity=0}]] sksreload10
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] sksreload10