event entity @s[hasitem=[{item=krep:m885,quantity=0},{item=krep:ammoboxc,quantity=0}]] spr15reload0
event entity @s[hasitem=[{item=krep:m885,quantity=1},{item=krep:ammoboxc,quantity=0}]] spr15reload1
event entity @s[hasitem=[{item=krep:m885,quantity=2},{item=krep:ammoboxc,quantity=0}]] spr15reload2
event entity @s[hasitem=[{item=krep:m885,quantity=3},{item=krep:ammoboxc,quantity=0}]] spr15reload3
event entity @s[hasitem=[{item=krep:m885,quantity=4},{item=krep:ammoboxc,quantity=0}]] spr15reload4
event entity @s[hasitem=[{item=krep:m885,quantity=5},{item=krep:ammoboxc,quantity=0}]] spr15reload5
event entity @s[hasitem=[{item=krep:m885,quantity=6},{item=krep:ammoboxc,quantity=0}]] spr15reload6
event entity @s[hasitem=[{item=krep:m885,quantity=7},{item=krep:ammoboxc,quantity=0}]] spr15reload7
event entity @s[hasitem=[{item=krep:m885,quantity=8},{item=krep:ammoboxc,quantity=0}]] spr15reload8
event entity @s[hasitem=[{item=krep:m885,quantity=9},{item=krep:ammoboxc,quantity=0}]] spr15reload9
event entity @s[hasitem=[{item=krep:m885,quantity=10},{item=krep:ammoboxc,quantity=0}]] spr15reload10
event entity @s[hasitem=[{item=krep:m885,quantity=11},{item=krep:ammoboxc,quantity=0}]] spr15reload11
event entity @s[hasitem=[{item=krep:m885,quantity=12},{item=krep:ammoboxc,quantity=0}]] spr15reload12
event entity @s[hasitem=[{item=krep:m885,quantity=13},{item=krep:ammoboxc,quantity=0}]] spr15reload13
event entity @s[hasitem=[{item=krep:m885,quantity=14},{item=krep:ammoboxc,quantity=0}]] spr15reload14
event entity @s[hasitem=[{item=krep:m885,quantity=15..},{item=krep:ammoboxc,quantity=0}]] spr15reload15
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] spr15reload15