event entity @s[hasitem=[{item=krep:ae50,quantity=0},{item=krep:ammoboxc,quantity=0}]] t50reload0
event entity @s[hasitem=[{item=krep:ae50,quantity=1},{item=krep:ammoboxc,quantity=0}]] t50reload1
event entity @s[hasitem=[{item=krep:ae50,quantity=2},{item=krep:ammoboxc,quantity=0}]] t50reload2
event entity @s[hasitem=[{item=krep:ae50,quantity=3},{item=krep:ammoboxc,quantity=0}]] t50reload3
event entity @s[hasitem=[{item=krep:ae50,quantity=4},{item=krep:ammoboxc,quantity=0}]] t50reload4
event entity @s[hasitem=[{item=krep:ae50,quantity=5},{item=krep:ammoboxc,quantity=0}]] t50reload5
event entity @s[hasitem=[{item=krep:ae50,quantity=6},{item=krep:ammoboxc,quantity=0}]] t50reload6
event entity @s[hasitem=[{item=krep:ae50,quantity=7},{item=krep:ammoboxc,quantity=0}]] t50reload7
event entity @s[hasitem=[{item=krep:ae50,quantity=8..},{item=krep:ammoboxc,quantity=0}]] t50reload8
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] t50reload8