event entity @s[hasitem=[{item=krep:wmr22,quantity=0},{item=krep:ammoboxc,quantity=0}]] taurus943reload0
event entity @s[hasitem=[{item=krep:wmr22,quantity=1},{item=krep:ammoboxc,quantity=0}]] taurus943reload1
event entity @s[hasitem=[{item=krep:wmr22,quantity=2},{item=krep:ammoboxc,quantity=0}]] taurus943reload2
event entity @s[hasitem=[{item=krep:wmr22,quantity=3},{item=krep:ammoboxc,quantity=0}]] taurus943reload3
event entity @s[hasitem=[{item=krep:wmr22,quantity=4},{item=krep:ammoboxc,quantity=0}]] taurus943reload4
event entity @s[hasitem=[{item=krep:wmr22,quantity=5},{item=krep:ammoboxc,quantity=0}]] taurus943reload5
event entity @s[hasitem=[{item=krep:wmr22,quantity=6},{item=krep:ammoboxc,quantity=0}]] taurus943reload6
event entity @s[hasitem=[{item=krep:wmr22,quantity=7},{item=krep:ammoboxc,quantity=0}]] taurus943reload7
event entity @s[hasitem=[{item=krep:wmr22,quantity=8..},{item=krep:ammoboxc,quantity=0}]] taurus943reload8
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] taurus943reload8