scoreboard objectives add m16a1 dummy m16a1
scoreboard players set @s m16a1 21
scoreboard objectives add sks dummy sks
scoreboard players set @s sks 11
scoreboard objectives add b93 dummy b93
scoreboard players set @s b93 21
scoreboard objectives add uzi dummy uzi
scoreboard players set @s uzi 21
scoreboard objectives add ump dummy ump
scoreboard players set @s ump 26
scoreboard objectives add m16 dummy m16
scoreboard players set @s m16 31
scoreboard objectives add m4a1 dummy m4a1
scoreboard players set @s m4a1 31
scoreboard objectives add g36 dummy g36
scoreboard players set @s g36 31
scoreboard objectives add g36sound dummy g36sound
scoreboard players set @s g36sound 0
scoreboard objectives add mp7sound dummy mp7sound
scoreboard players set @s mp7sound 0
scoreboard objectives add hk416sound dummy hk416sound
scoreboard players set @s hk416sound 0
scoreboard objectives add m4a1sound dummy m4a1sound
scoreboard players set @s m4a1sound 0
scoreboard objectives add vector dummy vector
scoreboard players set @s vector 21
scoreboard objectives add g3 dummy g3
scoreboard players set @s g3 21
scoreboard objectives add hk416 dummy hk416
scoreboard players set @s hk416 31

scoreboard objectives add fal dummy fal
scoreboard players set @s fal 21
scoreboard objectives add deagle dummy deagle
scoreboard players set @s deagle 8
scoreboard objectives add t50 dummy t50
scoreboard players set @s t50 9
scoreboard objectives add deagleg dummy deagleg
scoreboard players set @s deagleg 8
scoreboard objectives add m1911 dummy m1911
scoreboard players set @s m1911 8
scoreboard objectives add db dummy db
scoreboard players set @s db 2
scoreboard objectives add awp dummy awp
scoreboard players set @s awp 6
scoreboard objectives add m107 dummy m107
scoreboard players set @s m107 6
scoreboard objectives add m870 dummy m870
scoreboard players set @s m870 6
scoreboard objectives add m1014 dummy m1014
scoreboard players set @s m1014 8
scoreboard objectives add p90 dummy p90
scoreboard players set @s p90 51
scoreboard objectives add mp7 dummy mp7
scoreboard players set @s mp7 41
scoreboard objectives add scarh dummy scarh
scoreboard players set @s scarh 21
scoreboard objectives add mp5 dummy mp5
scoreboard players set @s mp5 31
scoreboard objectives add scarl dummy scarl
scoreboard players set @s scarl 31
scoreboard objectives add qbz95 dummy qbz95
scoreboard players set @s qbz95 31
scoreboard objectives add akm dummy akm
scoreboard players set @s akm 31
scoreboard objectives add aa12 dummy aa12
scoreboard players set @s aa12 11
scoreboard objectives add g17 dummy g17
scoreboard players set @s g17 18
scoreboard objectives add g18 dummy g18
scoreboard players set @s g18 18
scoreboard objectives add saiga12 dummy saiga12
scoreboard players set @s saiga12 5
scoreboard objectives add win308 dummy win308
scoreboard players set @s win308 320
scoreboard objectives add minigunoverheat dummy minigunoverheat
scoreboard players set @s minigunoverheat 0
scoreboard objectives add hk416select dummy hk416select
scoreboard players set @s hk416select 0
scoreboard objectives add gripselect dummy gripselect
scoreboard players set @s gripselect 0
scoreboard objectives add miscselect dummy miscselect
scoreboard players set @s miscselect 0
scoreboard objectives add scopeselect dummy scopeselect
scoreboard players set @s scopeselect 0
scoreboard objectives add stockselect dummy stockselect
scoreboard players set @s stockselect 0
scoreboard objectives add cp dummy cp
scoreboard players set @s cp 6
scoreboard objectives add qbz191 dummy qbz191
scoreboard players set @s qbz191 31
scoreboard objectives add p320 dummy p320
scoreboard players set @s p320 13
scoreboard objectives add mk14 dummy mk14
scoreboard players set @s mk14 21
scoreboard objectives add evolys dummy evolys
scoreboard players set @s evolys 76
scoreboard objectives add m249 dummy m249
scoreboard players set @s m249 101
scoreboard objectives add type81 dummy type81
scoreboard players set @s type81 31