event entity @s[hasitem=[{item=krep:m43,quantity=0},{item=krep:ammoboxc,quantity=0}]] type81reload0
event entity @s[hasitem=[{item=krep:m43,quantity=1},{item=krep:ammoboxc,quantity=0}]] type81reload1
event entity @s[hasitem=[{item=krep:m43,quantity=2},{item=krep:ammoboxc,quantity=0}]] type81reload2
event entity @s[hasitem=[{item=krep:m43,quantity=3},{item=krep:ammoboxc,quantity=0}]] type81reload3
event entity @s[hasitem=[{item=krep:m43,quantity=4},{item=krep:ammoboxc,quantity=0}]] type81reload4
event entity @s[hasitem=[{item=krep:m43,quantity=5},{item=krep:ammoboxc,quantity=0}]] type81reload5
event entity @s[hasitem=[{item=krep:m43,quantity=6},{item=krep:ammoboxc,quantity=0}]] type81reload6
event entity @s[hasitem=[{item=krep:m43,quantity=7},{item=krep:ammoboxc,quantity=0}]] type81reload7
event entity @s[hasitem=[{item=krep:m43,quantity=8},{item=krep:ammoboxc,quantity=0}]] type81reload8
event entity @s[hasitem=[{item=krep:m43,quantity=9},{item=krep:ammoboxc,quantity=0}]] type81reload9
event entity @s[hasitem=[{item=krep:m43,quantity=10},{item=krep:ammoboxc,quantity=0}]] type81reload10
event entity @s[hasitem=[{item=krep:m43,quantity=11},{item=krep:ammoboxc,quantity=0}]] type81reload11
event entity @s[hasitem=[{item=krep:m43,quantity=12},{item=krep:ammoboxc,quantity=0}]] type81reload12
event entity @s[hasitem=[{item=krep:m43,quantity=13},{item=krep:ammoboxc,quantity=0}]] type81reload13
event entity @s[hasitem=[{item=krep:m43,quantity=14},{item=krep:ammoboxc,quantity=0}]] type81reload14
event entity @s[hasitem=[{item=krep:m43,quantity=15},{item=krep:ammoboxc,quantity=0}]] type81reload15
event entity @s[hasitem=[{item=krep:m43,quantity=16},{item=krep:ammoboxc,quantity=0}]] type81reload16
event entity @s[hasitem=[{item=krep:m43,quantity=17},{item=krep:ammoboxc,quantity=0}]] type81reload17
event entity @s[hasitem=[{item=krep:m43,quantity=18},{item=krep:ammoboxc,quantity=0}]] type81reload18
event entity @s[hasitem=[{item=krep:m43,quantity=19},{item=krep:ammoboxc,quantity=0}]] type81reload19
event entity @s[hasitem=[{item=krep:m43,quantity=20},{item=krep:ammoboxc,quantity=0}]] type81reload20
event entity @s[hasitem=[{item=krep:m43,quantity=21},{item=krep:ammoboxc,quantity=0}]] type81reload21
event entity @s[hasitem=[{item=krep:m43,quantity=22},{item=krep:ammoboxc,quantity=0}]] type81reload22
event entity @s[hasitem=[{item=krep:m43,quantity=23},{item=krep:ammoboxc,quantity=0}]] type81reload23
event entity @s[hasitem=[{item=krep:m43,quantity=24},{item=krep:ammoboxc,quantity=0}]] type81reload24
event entity @s[hasitem=[{item=krep:m43,quantity=25},{item=krep:ammoboxc,quantity=0}]] type81reload25
event entity @s[hasitem=[{item=krep:m43,quantity=26},{item=krep:ammoboxc,quantity=0}]] type81reload26
event entity @s[hasitem=[{item=krep:m43,quantity=27},{item=krep:ammoboxc,quantity=0}]] type81reload27
event entity @s[hasitem=[{item=krep:m43,quantity=28},{item=krep:ammoboxc,quantity=0}]] type81reload28
event entity @s[hasitem=[{item=krep:m43,quantity=29},{item=krep:ammoboxc,quantity=0}]] type81reload29
event entity @s[hasitem=[{item=krep:m43,quantity=30..},{item=krep:ammoboxc,quantity=0}]] type81reload30
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] type81reload30