event entity @s[hasitem=[{item=krep:acp45,quantity=0},{item=krep:ammoboxc,quantity=0}]] umpreload0
event entity @s[hasitem=[{item=krep:acp45,quantity=1},{item=krep:ammoboxc,quantity=0}]] umpreload1
event entity @s[hasitem=[{item=krep:acp45,quantity=2},{item=krep:ammoboxc,quantity=0}]] umpreload2
event entity @s[hasitem=[{item=krep:acp45,quantity=3},{item=krep:ammoboxc,quantity=0}]] umpreload3
event entity @s[hasitem=[{item=krep:acp45,quantity=4},{item=krep:ammoboxc,quantity=0}]] umpreload4
event entity @s[hasitem=[{item=krep:acp45,quantity=5},{item=krep:ammoboxc,quantity=0}]] umpreload5
event entity @s[hasitem=[{item=krep:acp45,quantity=6},{item=krep:ammoboxc,quantity=0}]] umpreload6
event entity @s[hasitem=[{item=krep:acp45,quantity=7},{item=krep:ammoboxc,quantity=0}]] umpreload7
event entity @s[hasitem=[{item=krep:acp45,quantity=8},{item=krep:ammoboxc,quantity=0}]] umpreload8
event entity @s[hasitem=[{item=krep:acp45,quantity=9},{item=krep:ammoboxc,quantity=0}]] umpreload9
event entity @s[hasitem=[{item=krep:acp45,quantity=10},{item=krep:ammoboxc,quantity=0}]] umpreload10
event entity @s[hasitem=[{item=krep:acp45,quantity=11},{item=krep:ammoboxc,quantity=0}]] umpreload11
event entity @s[hasitem=[{item=krep:acp45,quantity=12},{item=krep:ammoboxc,quantity=0}]] umpreload12
event entity @s[hasitem=[{item=krep:acp45,quantity=13},{item=krep:ammoboxc,quantity=0}]] umpreload13
event entity @s[hasitem=[{item=krep:acp45,quantity=14},{item=krep:ammoboxc,quantity=0}]] umpreload14
event entity @s[hasitem=[{item=krep:acp45,quantity=15},{item=krep:ammoboxc,quantity=0}]] umpreload15
event entity @s[hasitem=[{item=krep:acp45,quantity=16},{item=krep:ammoboxc,quantity=0}]] umpreload16
event entity @s[hasitem=[{item=krep:acp45,quantity=17},{item=krep:ammoboxc,quantity=0}]] umpreload17
event entity @s[hasitem=[{item=krep:acp45,quantity=18},{item=krep:ammoboxc,quantity=0}]] umpreload18
event entity @s[hasitem=[{item=krep:acp45,quantity=19},{item=krep:ammoboxc,quantity=0}]] umpreload19
event entity @s[hasitem=[{item=krep:acp45,quantity=20},{item=krep:ammoboxc,quantity=0}]] umpreload20
event entity @s[hasitem=[{item=krep:acp45,quantity=21},{item=krep:ammoboxc,quantity=0}]] umpreload21
event entity @s[hasitem=[{item=krep:acp45,quantity=22},{item=krep:ammoboxc,quantity=0}]] umpreload22
event entity @s[hasitem=[{item=krep:acp45,quantity=23},{item=krep:ammoboxc,quantity=0}]] umpreload23
event entity @s[hasitem=[{item=krep:acp45,quantity=24},{item=krep:ammoboxc,quantity=0}]] umpreload24
event entity @s[hasitem=[{item=krep:acp45,quantity=25..},{item=krep:ammoboxc,quantity=0}]] umpreload25
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] umpreload25