clear @s[m=!c,scores={ump=24},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 1
clear @s[m=!c,scores={ump=23},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 2
clear @s[m=!c,scores={ump=22},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 3
clear @s[m=!c,scores={ump=21},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 4
clear @s[m=!c,scores={ump=20},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 5
clear @s[m=!c,scores={ump=19},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 6
clear @s[m=!c,scores={ump=18},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 7
clear @s[m=!c,scores={ump=17},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 8
clear @s[m=!c,scores={ump=16},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 9
clear @s[m=!c,scores={ump=15},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 10
clear @s[m=!c,scores={ump=14},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 11
clear @s[m=!c,scores={ump=13},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 12
clear @s[m=!c,scores={ump=12},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 13
clear @s[m=!c,scores={ump=11},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 14
clear @s[m=!c,scores={ump=10},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 15
clear @s[m=!c,scores={ump=9},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 16
clear @s[m=!c,scores={ump=8},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 17
clear @s[m=!c,scores={ump=7},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 18
clear @s[m=!c,scores={ump=6},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 19
clear @s[m=!c,scores={ump=5},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 20
clear @s[m=!c,scores={ump=4},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 21
clear @s[m=!c,scores={ump=3},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 22
clear @s[m=!c,scores={ump=2},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 23
clear @s[m=!c,scores={ump=1},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 24
clear @s[m=!c,scores={ump=0},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 25