event entity @s[hasitem=[{item=krep:mm9,quantity=0},{item=krep:ammoboxc,quantity=0}]] uzireload0
event entity @s[hasitem=[{item=krep:mm9,quantity=1},{item=krep:ammoboxc,quantity=0}]] uzireload1
event entity @s[hasitem=[{item=krep:mm9,quantity=2},{item=krep:ammoboxc,quantity=0}]] uzireload2
event entity @s[hasitem=[{item=krep:mm9,quantity=3},{item=krep:ammoboxc,quantity=0}]] uzireload3
event entity @s[hasitem=[{item=krep:mm9,quantity=4},{item=krep:ammoboxc,quantity=0}]] uzireload4
event entity @s[hasitem=[{item=krep:mm9,quantity=5},{item=krep:ammoboxc,quantity=0}]] uzireload5
event entity @s[hasitem=[{item=krep:mm9,quantity=6},{item=krep:ammoboxc,quantity=0}]] uzireload6
event entity @s[hasitem=[{item=krep:mm9,quantity=7},{item=krep:ammoboxc,quantity=0}]] uzireload7
event entity @s[hasitem=[{item=krep:mm9,quantity=8},{item=krep:ammoboxc,quantity=0}]] uzireload8
event entity @s[hasitem=[{item=krep:mm9,quantity=9},{item=krep:ammoboxc,quantity=0}]] uzireload9
event entity @s[hasitem=[{item=krep:mm9,quantity=10},{item=krep:ammoboxc,quantity=0}]] uzireload10
event entity @s[hasitem=[{item=krep:mm9,quantity=11},{item=krep:ammoboxc,quantity=0}]] uzireload11
event entity @s[hasitem=[{item=krep:mm9,quantity=12},{item=krep:ammoboxc,quantity=0}]] uzireload12
event entity @s[hasitem=[{item=krep:mm9,quantity=13},{item=krep:ammoboxc,quantity=0}]] uzireload13
event entity @s[hasitem=[{item=krep:mm9,quantity=14},{item=krep:ammoboxc,quantity=0}]] uzireload14
event entity @s[hasitem=[{item=krep:mm9,quantity=15},{item=krep:ammoboxc,quantity=0}]] uzireload15
event entity @s[hasitem=[{item=krep:mm9,quantity=16},{item=krep:ammoboxc,quantity=0}]] uzireload16
event entity @s[hasitem=[{item=krep:mm9,quantity=17},{item=krep:ammoboxc,quantity=0}]] uzireload17
event entity @s[hasitem=[{item=krep:mm9,quantity=18},{item=krep:ammoboxc,quantity=0}]] uzireload18
event entity @s[hasitem=[{item=krep:mm9,quantity=19},{item=krep:ammoboxc,quantity=0}]] uzireload19
event entity @s[hasitem=[{item=krep:mm9,quantity=20..},{item=krep:ammoboxc,quantity=0}]] uzireload20
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] uzireload20