clear @s[m=!c,scores={uzi=19},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 1
clear @s[m=!c,scores={uzi=18},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 2
clear @s[m=!c,scores={uzi=17},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 3
clear @s[m=!c,scores={uzi=16},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 4
clear @s[m=!c,scores={uzi=15},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 5
clear @s[m=!c,scores={uzi=14},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 6
clear @s[m=!c,scores={uzi=13},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 7
clear @s[m=!c,scores={uzi=12},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 8
clear @s[m=!c,scores={uzi=11},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 9
clear @s[m=!c,scores={uzi=10},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 10
clear @s[m=!c,scores={uzi=9},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 11
clear @s[m=!c,scores={uzi=8},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 12
clear @s[m=!c,scores={uzi=7},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 13
clear @s[m=!c,scores={uzi=6},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 14
clear @s[m=!c,scores={uzi=5},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 15
clear @s[m=!c,scores={uzi=4},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 16
clear @s[m=!c,scores={uzi=3},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 17
clear @s[m=!c,scores={uzi=2},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 18
clear @s[m=!c,scores={uzi=1},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 19
clear @s[m=!c,scores={uzi=0},hasitem={item=krep:ammoboxc,quantity=0}] krep:mm9 0 20