clear @s[m=!c,scores={vector=39},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 1
clear @s[m=!c,scores={vector=38},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 2
clear @s[m=!c,scores={vector=37},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 3
clear @s[m=!c,scores={vector=36},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 4
clear @s[m=!c,scores={vector=35},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 5
clear @s[m=!c,scores={vector=34},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 6
clear @s[m=!c,scores={vector=33},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 7
clear @s[m=!c,scores={vector=32},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 8
clear @s[m=!c,scores={vector=31},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 9
clear @s[m=!c,scores={vector=30},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 10
clear @s[m=!c,scores={vector=29},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 11
clear @s[m=!c,scores={vector=28},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 12
clear @s[m=!c,scores={vector=27},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 13
clear @s[m=!c,scores={vector=26},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 14
clear @s[m=!c,scores={vector=25},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 15
clear @s[m=!c,scores={vector=24},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 16
clear @s[m=!c,scores={vector=23},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 17
clear @s[m=!c,scores={vector=22},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 18
clear @s[m=!c,scores={vector=21},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 19
clear @s[m=!c,scores={vector=20},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 20
clear @s[m=!c,scores={vector=19},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 21
clear @s[m=!c,scores={vector=18},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 22
clear @s[m=!c,scores={vector=17},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 23
clear @s[m=!c,scores={vector=16},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 24
clear @s[m=!c,scores={vector=15},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 25
clear @s[m=!c,scores={vector=14},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 26
clear @s[m=!c,scores={vector=13},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 27
clear @s[m=!c,scores={vector=12},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 28
clear @s[m=!c,scores={vector=11},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 29
clear @s[m=!c,scores={vector=10},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 30
clear @s[m=!c,scores={vector=9},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 31
clear @s[m=!c,scores={vector=8},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 32
clear @s[m=!c,scores={vector=7},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 33
clear @s[m=!c,scores={vector=6},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 34
clear @s[m=!c,scores={vector=5},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 35
clear @s[m=!c,scores={vector=4},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 36
clear @s[m=!c,scores={vector=3},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 37
clear @s[m=!c,scores={vector=2},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 38
clear @s[m=!c,scores={vector=1},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 39
clear @s[m=!c,scores={vector=0},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 40