clear @s[m=!c,scores={vector=19},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 1
clear @s[m=!c,scores={vector=18},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 2
clear @s[m=!c,scores={vector=17},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 3
clear @s[m=!c,scores={vector=16},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 4
clear @s[m=!c,scores={vector=15},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 5
clear @s[m=!c,scores={vector=14},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 6
clear @s[m=!c,scores={vector=13},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 7
clear @s[m=!c,scores={vector=12},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 8
clear @s[m=!c,scores={vector=11},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 9
clear @s[m=!c,scores={vector=10},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 10
clear @s[m=!c,scores={vector=9},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 11
clear @s[m=!c,scores={vector=8},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 12
clear @s[m=!c,scores={vector=7},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 13
clear @s[m=!c,scores={vector=6},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 14
clear @s[m=!c,scores={vector=5},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 15
clear @s[m=!c,scores={vector=4},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 16
clear @s[m=!c,scores={vector=3},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 17
clear @s[m=!c,scores={vector=2},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 18
clear @s[m=!c,scores={vector=1},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 19
clear @s[m=!c,scores={vector=0},hasitem={item=krep:ammoboxc,quantity=0}] krep:acp45 0 20