event entity @s[hasitem=[{item=krep:acp45,quantity=0},{item=krep:ammoboxc,quantity=0}]] vectorreload0
event entity @s[hasitem=[{item=krep:acp45,quantity=1},{item=krep:ammoboxc,quantity=0}]] vectorreload1
event entity @s[hasitem=[{item=krep:acp45,quantity=2},{item=krep:ammoboxc,quantity=0}]] vectorreload2
event entity @s[hasitem=[{item=krep:acp45,quantity=3},{item=krep:ammoboxc,quantity=0}]] vectorreload3
event entity @s[hasitem=[{item=krep:acp45,quantity=4},{item=krep:ammoboxc,quantity=0}]] vectorreload4
event entity @s[hasitem=[{item=krep:acp45,quantity=5},{item=krep:ammoboxc,quantity=0}]] vectorreload5
event entity @s[hasitem=[{item=krep:acp45,quantity=6},{item=krep:ammoboxc,quantity=0}]] vectorreload6
event entity @s[hasitem=[{item=krep:acp45,quantity=7},{item=krep:ammoboxc,quantity=0}]] vectorreload7
event entity @s[hasitem=[{item=krep:acp45,quantity=8},{item=krep:ammoboxc,quantity=0}]] vectorreload8
event entity @s[hasitem=[{item=krep:acp45,quantity=9},{item=krep:ammoboxc,quantity=0}]] vectorreload9
event entity @s[hasitem=[{item=krep:acp45,quantity=10},{item=krep:ammoboxc,quantity=0}]] vectorreload10
event entity @s[hasitem=[{item=krep:acp45,quantity=11},{item=krep:ammoboxc,quantity=0}]] vectorreload11
event entity @s[hasitem=[{item=krep:acp45,quantity=12},{item=krep:ammoboxc,quantity=0}]] vectorreload12
event entity @s[hasitem=[{item=krep:acp45,quantity=13},{item=krep:ammoboxc,quantity=0}]] vectorreload13
event entity @s[hasitem=[{item=krep:acp45,quantity=14},{item=krep:ammoboxc,quantity=0}]] vectorreload14
event entity @s[hasitem=[{item=krep:acp45,quantity=15},{item=krep:ammoboxc,quantity=0}]] vectorreload15
event entity @s[hasitem=[{item=krep:acp45,quantity=16},{item=krep:ammoboxc,quantity=0}]] vectorreload16
event entity @s[hasitem=[{item=krep:acp45,quantity=17},{item=krep:ammoboxc,quantity=0}]] vectorreload17
event entity @s[hasitem=[{item=krep:acp45,quantity=18},{item=krep:ammoboxc,quantity=0}]] vectorreload18
event entity @s[hasitem=[{item=krep:acp45,quantity=19},{item=krep:ammoboxc,quantity=0}]] vectorreload19
event entity @s[hasitem=[{item=krep:acp45,quantity=20},{item=krep:ammoboxc,quantity=0}]] vectorreload20
event entity @s[hasitem=[{item=krep:acp45,quantity=21},{item=krep:ammoboxc,quantity=0}]] vectorreload21
event entity @s[hasitem=[{item=krep:acp45,quantity=22},{item=krep:ammoboxc,quantity=0}]] vectorreload22
event entity @s[hasitem=[{item=krep:acp45,quantity=23},{item=krep:ammoboxc,quantity=0}]] vectorreload23
event entity @s[hasitem=[{item=krep:acp45,quantity=24},{item=krep:ammoboxc,quantity=0}]] vectorreload24
event entity @s[hasitem=[{item=krep:acp45,quantity=25},{item=krep:ammoboxc,quantity=0}]] vectorreload25
event entity @s[hasitem=[{item=krep:acp45,quantity=26},{item=krep:ammoboxc,quantity=0}]] vectorreload26
event entity @s[hasitem=[{item=krep:acp45,quantity=27},{item=krep:ammoboxc,quantity=0}]] vectorreload27
event entity @s[hasitem=[{item=krep:acp45,quantity=28},{item=krep:ammoboxc,quantity=0}]] vectorreload28
event entity @s[hasitem=[{item=krep:acp45,quantity=29},{item=krep:ammoboxc,quantity=0}]] vectorreload29
event entity @s[hasitem=[{item=krep:acp45,quantity=30},{item=krep:ammoboxc,quantity=0}]] vectorreload30
event entity @s[hasitem=[{item=krep:acp45,quantity=31},{item=krep:ammoboxc,quantity=0}]] vectorreload31
event entity @s[hasitem=[{item=krep:acp45,quantity=32},{item=krep:ammoboxc,quantity=0}]] vectorreload32
event entity @s[hasitem=[{item=krep:acp45,quantity=33},{item=krep:ammoboxc,quantity=0}]] vectorreload33
event entity @s[hasitem=[{item=krep:acp45,quantity=34},{item=krep:ammoboxc,quantity=0}]] vectorreload34
event entity @s[hasitem=[{item=krep:acp45,quantity=35},{item=krep:ammoboxc,quantity=0}]] vectorreload35
event entity @s[hasitem=[{item=krep:acp45,quantity=36},{item=krep:ammoboxc,quantity=0}]] vectorreload36
event entity @s[hasitem=[{item=krep:acp45,quantity=37},{item=krep:ammoboxc,quantity=0}]] vectorreload37
event entity @s[hasitem=[{item=krep:acp45,quantity=38},{item=krep:ammoboxc,quantity=0}]] vectorreload38
event entity @s[hasitem=[{item=krep:acp45,quantity=39},{item=krep:ammoboxc,quantity=0}]] vectorreload39
event entity @s[hasitem=[{item=krep:acp45,quantity=40},{item=krep:ammoboxc,quantity=0}]] vectorreload40
event entity @s[hasitem=[{item=krep:acp45,quantity=41},{item=krep:ammoboxc,quantity=0}]] vectorreload41
event entity @s[hasitem=[{item=krep:acp45,quantity=42},{item=krep:ammoboxc,quantity=0}]] vectorreload42
event entity @s[hasitem=[{item=krep:acp45,quantity=43},{item=krep:ammoboxc,quantity=0}]] vectorreload43
event entity @s[hasitem=[{item=krep:acp45,quantity=44},{item=krep:ammoboxc,quantity=0}]] vectorreload44
event entity @s[hasitem=[{item=krep:acp45,quantity=45},{item=krep:ammoboxc,quantity=0}]] vectorreload45
event entity @s[hasitem=[{item=krep:acp45,quantity=46},{item=krep:ammoboxc,quantity=0}]] vectorreload46
event entity @s[hasitem=[{item=krep:acp45,quantity=47},{item=krep:ammoboxc,quantity=0}]] vectorreload47
event entity @s[hasitem=[{item=krep:acp45,quantity=48},{item=krep:ammoboxc,quantity=0}]] vectorreload48
event entity @s[hasitem=[{item=krep:acp45,quantity=49},{item=krep:ammoboxc,quantity=0}]] vectorreload49
event entity @s[hasitem=[{item=krep:acp45,quantity=50..},{item=krep:ammoboxc,quantity=0}]] vectorreload50
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] vectorreload50