event entity @s[hasitem=[{item=krep:acp45,quantity=0},{item=krep:ammoboxc,quantity=0}]] vectorreload0
event entity @s[hasitem=[{item=krep:acp45,quantity=1},{item=krep:ammoboxc,quantity=0}]] vectorreload1
event entity @s[hasitem=[{item=krep:acp45,quantity=2},{item=krep:ammoboxc,quantity=0}]] vectorreload2
event entity @s[hasitem=[{item=krep:acp45,quantity=3},{item=krep:ammoboxc,quantity=0}]] vectorreload3
event entity @s[hasitem=[{item=krep:acp45,quantity=4},{item=krep:ammoboxc,quantity=0}]] vectorreload4
event entity @s[hasitem=[{item=krep:acp45,quantity=5},{item=krep:ammoboxc,quantity=0}]] vectorreload5
event entity @s[hasitem=[{item=krep:acp45,quantity=6},{item=krep:ammoboxc,quantity=0}]] vectorreload6
event entity @s[hasitem=[{item=krep:acp45,quantity=7},{item=krep:ammoboxc,quantity=0}]] vectorreload7
event entity @s[hasitem=[{item=krep:acp45,quantity=8},{item=krep:ammoboxc,quantity=0}]] vectorreload8
event entity @s[hasitem=[{item=krep:acp45,quantity=9},{item=krep:ammoboxc,quantity=0}]] vectorreload9
event entity @s[hasitem=[{item=krep:acp45,quantity=10},{item=krep:ammoboxc,quantity=0}]] vectorreload10
event entity @s[hasitem=[{item=krep:acp45,quantity=11},{item=krep:ammoboxc,quantity=0}]] vectorreload11
event entity @s[hasitem=[{item=krep:acp45,quantity=12},{item=krep:ammoboxc,quantity=0}]] vectorreload12
event entity @s[hasitem=[{item=krep:acp45,quantity=13},{item=krep:ammoboxc,quantity=0}]] vectorreload13
event entity @s[hasitem=[{item=krep:acp45,quantity=14},{item=krep:ammoboxc,quantity=0}]] vectorreload14
event entity @s[hasitem=[{item=krep:acp45,quantity=15},{item=krep:ammoboxc,quantity=0}]] vectorreload15
event entity @s[hasitem=[{item=krep:acp45,quantity=16},{item=krep:ammoboxc,quantity=0}]] vectorreload16
event entity @s[hasitem=[{item=krep:acp45,quantity=17},{item=krep:ammoboxc,quantity=0}]] vectorreload17
event entity @s[hasitem=[{item=krep:acp45,quantity=18},{item=krep:ammoboxc,quantity=0}]] vectorreload18
event entity @s[hasitem=[{item=krep:acp45,quantity=19},{item=krep:ammoboxc,quantity=0}]] vectorreload19
event entity @s[hasitem=[{item=krep:acp45,quantity=20..},{item=krep:ammoboxc,quantity=0}]] vectorreload20
event entity @s[hasitem={item=krep:ammoboxc,quantity=1..}] vectorreload20